VERSION 1
ID 7
REFERENCE ++NIX
DESCRIPTION "SoF Plus PLus Linux."
COUNT 5
INDEX 0
{
  REFERENCE LAYOUT_CUSTOM
  FLAGS SP_FLAG_LAYOUT
  TEXT_ENGLISH "%s"
}
INDEX 1
{
  REFERENCE CREDIT_CUSTOM
  FLAGS SP_FLAG_CREDIT
  TEXT_ENGLISH "%s"
}
INDEX 2
{
  REFERENCE CENTER_LOWER_CUSTOM
  FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
  TEXT_ENGLISH "%s"
}
INDEX 3
{
  REFERENCE CINEMATIC_CUSTOM
  FLAGS SP_FLAG_TYPEAMATIC 
  TEXT_ENGLISH "%s"
}
INDEX 4
{
  REFERENCE CENTER_CUSTOM
  FLAGS SP_FLAG_CENTERED
  TEXT_ENGLISH "%s"
}
