VERSION 1
ID 14
REFERENCE KEY
DESCRIPTION "The keymap converter"
COUNT 138
INDEX 0
{
   REFERENCE MOUSE1
   TEXT_ENGLISH "MOUSE1"
   TEXT_GERMAN "MAUS 1"
   TEXT_FRENCH "SOURIS1"
}
INDEX 1
{
   REFERENCE MOUSE2
   TEXT_ENGLISH "MOUSE2"
   TEXT_GERMAN "MAUS 2"
   TEXT_FRENCH "SOURIS2"
}
INDEX 2
{
   REFERENCE MOUSE3
   TEXT_ENGLISH "MOUSE3"
   TEXT_GERMAN "MAUS 3"
   TEXT_FRENCH "SOURIS3"
}
INDEX 3
{
   REFERENCE MOUSE4
   TEXT_ENGLISH "MOUSE4"
   TEXT_GERMAN "MAUS 4"
   TEXT_FRENCH "SOURIS4"
}
INDEX 4
{
   REFERENCE MOUSE5
   TEXT_ENGLISH "MOUSE5"
   TEXT_GERMAN "MAUS 5"
   TEXT_FRENCH "SOURIS5"
}
INDEX 5
{
   REFERENCE BACKSPACE
   TEXT_ENGLISH "BACKSPACE"
   TEXT_GERMAN "RÜCKTASTE"
   TEXT_FRENCH "RETOUR"
}
INDEX 6
{
   REFERENCE TAB
   TEXT_ENGLISH "TAB"
   TEXT_GERMAN "TAB"
   TEXT_FRENCH "TAB"
}
INDEX 7
{
   REFERENCE ENTER
   TEXT_ENGLISH "ENTER"
   TEXT_GERMAN "EINGABETASTE"
   TEXT_FRENCH "ENTREE"
}
INDEX 8
{
   REFERENCE LSHIFT
   TEXT_ENGLISH "LSHIFT"
   TEXT_GERMAN "L.  UMSCHALTT."
   TEXT_FRENCH "MAJG"
}
INDEX 9
{
   REFERENCE LCTRL
   TEXT_ENGLISH "LCTRL"
   TEXT_GERMAN "L. STRG"
   TEXT_FRENCH "CTRLG"
}
INDEX 10
{
   REFERENCE LALT
   TEXT_ENGLISH "LALT"
   TEXT_GERMAN "ALT"
   TEXT_FRENCH "ALT"
}
INDEX 11
{
   REFERENCE PAUSE
   TEXT_ENGLISH "PAUSE"
   TEXT_GERMAN "PAUSE"
   TEXT_FRENCH "PAUSE"
}
INDEX 12
{
   REFERENCE CAPS
   TEXT_ENGLISH "CAPS"
   TEXT_GERMAN "FESTSTELLT."
   TEXT_FRENCH "VERRMAJ"
}
INDEX 13
{
   REFERENCE RSHIFT
   TEXT_ENGLISH "RSHIFT"
   TEXT_GERMAN "R. UMSCHALTT."
   TEXT_FRENCH "MAJD"
}
INDEX 14
{
   REFERENCE RCTRL
   TEXT_ENGLISH "RCTRL"
   TEXT_GERMAN "R. STRG"
   TEXT_FRENCH "CTRLD"
}
INDEX 15
{
   REFERENCE RALT
   TEXT_ENGLISH "RALT"
   TEXT_GERMAN "ALT GR"
   TEXT_FRENCH "ALTGR"
}
INDEX 16
{
   REFERENCE MWHEELDOWN
   TEXT_ENGLISH "MWHEELDOWN"
   TEXT_GERMAN "MAUSRAD UNTEN"
   TEXT_FRENCH "MOLETTEBAS"
}
INDEX 17
{
   REFERENCE MWHEELUP
   TEXT_ENGLISH "MWHEELUP"
   TEXT_GERMAN "MAUSRAD OBEN"
   TEXT_FRENCH "MOLETTEHT"
}
INDEX 18
{
   REFERENCE ESCAPE
   TEXT_ENGLISH "ESCAPE"
   TEXT_GERMAN "ESC"
   TEXT_FRENCH "ECHAP"
}
INDEX 19
{
   REFERENCE SPACE
   TEXT_ENGLISH "SPACE"
   TEXT_GERMAN "LEERTASTE"
   TEXT_FRENCH "ESPACE"
}
INDEX 20
{
   REFERENCE PGUP
   TEXT_ENGLISH "PGUP"
   TEXT_GERMAN "BILD-AUF"
   TEXT_FRENCH "PGHAUT"
}
INDEX 21
{
   REFERENCE PGDN
   TEXT_ENGLISH "PGDN"
   TEXT_GERMAN "BILD-AB"
   TEXT_FRENCH "PGBAS"
}
INDEX 22
{
   REFERENCE END
   TEXT_ENGLISH "END"
   TEXT_GERMAN "ENDE"
   TEXT_FRENCH "FIN"
}
INDEX 23
{
   REFERENCE HOME
   TEXT_ENGLISH "HOME"
   TEXT_GERMAN "POS 1"
   TEXT_FRENCH "ORIGINE"
}
INDEX 24
{
   REFERENCE LEFTARROW
   TEXT_ENGLISH "LEFTARROW"
   TEXT_GERMAN "LINKE PFEILTASTE"
   TEXT_FRENCH "GAUCHE"
}
INDEX 25
{
   REFERENCE RIGHTARROW
   TEXT_ENGLISH "RIGHTARROW"
   TEXT_GERMAN "RECHTE PFEILTASTE"
   TEXT_FRENCH "DROITE"
}
INDEX 26
{
   REFERENCE DOWNARROW
   TEXT_ENGLISH "DOWNARROW"
   TEXT_GERMAN "PFEILTASTE ABWÄRTS"
   TEXT_FRENCH "BAS"
}
INDEX 27
{
   REFERENCE INS
   TEXT_ENGLISH "INS"
   TEXT_GERMAN "EINFG"
   TEXT_FRENCH "INSER"
}
INDEX 28
{
   REFERENCE DEL
   TEXT_ENGLISH "DEL"
   TEXT_GERMAN "ENTF"
   TEXT_FRENCH "SUPPR"
}
INDEX 29
{
   REFERENCE 0
   TEXT_ENGLISH "0"
   TEXT_GERMAN "0"
}
INDEX 30
{
   REFERENCE 1
   TEXT_ENGLISH "1"
   TEXT_GERMAN "1"
}
INDEX 31
{
   REFERENCE 2
   TEXT_ENGLISH "2"
   TEXT_GERMAN "2"
}
INDEX 32
{
   REFERENCE 3
   TEXT_ENGLISH "3"
   TEXT_GERMAN "3"
}
INDEX 33
{
   REFERENCE 4
   TEXT_ENGLISH "4"
   TEXT_GERMAN "4"
}
INDEX 34
{
   REFERENCE 5
   TEXT_ENGLISH "5"
   TEXT_GERMAN "5"
}
INDEX 35
{
   REFERENCE 6
   TEXT_ENGLISH "6"
   TEXT_GERMAN "6"
}
INDEX 36
{
   REFERENCE 7
   TEXT_ENGLISH "7"
   TEXT_GERMAN "7"
}
INDEX 37
{
   REFERENCE 8
   TEXT_ENGLISH "8"
   TEXT_GERMAN "8"
}
INDEX 38
{
   REFERENCE 9
   TEXT_ENGLISH "9"
   TEXT_GERMAN "9"
}
INDEX 39
{
   REFERENCE A
   TEXT_ENGLISH "A"
   TEXT_GERMAN "A"
}
INDEX 40
{
   REFERENCE B
   TEXT_ENGLISH "B"
   TEXT_GERMAN "B"
}
INDEX 41
{
   REFERENCE C
   TEXT_ENGLISH "C"
   TEXT_GERMAN "C"
}
INDEX 42
{
   REFERENCE D
   TEXT_ENGLISH "D"
   TEXT_GERMAN "D"
}
INDEX 43
{
   REFERENCE E
   TEXT_ENGLISH "E"
   TEXT_GERMAN "E"
}
INDEX 44
{
   REFERENCE F
   TEXT_ENGLISH "F"
   TEXT_GERMAN "F"
}
INDEX 45
{
   REFERENCE G
   TEXT_ENGLISH "G"
   TEXT_GERMAN "G"
}
INDEX 46
{
   REFERENCE H
   TEXT_ENGLISH "H"
   TEXT_GERMAN "H"
}
INDEX 47
{
   REFERENCE I
   TEXT_ENGLISH "I"
   TEXT_GERMAN "I"
}
INDEX 48
{
   REFERENCE J
   TEXT_ENGLISH "J"
   TEXT_GERMAN "J"
}
INDEX 49
{
   REFERENCE K
   TEXT_ENGLISH "K"
   TEXT_GERMAN "K"
}
INDEX 50
{
   REFERENCE L
   TEXT_ENGLISH "L"
   TEXT_GERMAN "L"
}
INDEX 51
{
   REFERENCE M
   TEXT_ENGLISH "M"
   TEXT_GERMAN "M"
}
INDEX 52
{
   REFERENCE N
   TEXT_ENGLISH "N"
   TEXT_GERMAN "N"
}
INDEX 53
{
   REFERENCE O
   TEXT_ENGLISH "O"
   TEXT_GERMAN "O"
}
INDEX 54
{
   REFERENCE P
   TEXT_ENGLISH "P"
   TEXT_GERMAN "P"
}
INDEX 55
{
   REFERENCE Q
   TEXT_ENGLISH "Q"
   TEXT_GERMAN "Q"
}
INDEX 56
{
   REFERENCE R
   TEXT_ENGLISH "R"
   TEXT_GERMAN "R"
}
INDEX 57
{
   REFERENCE S
   TEXT_ENGLISH "S"
   TEXT_GERMAN "S"
}
INDEX 58
{
   REFERENCE T
   TEXT_ENGLISH "T"
   TEXT_GERMAN "T"
}
INDEX 59
{
   REFERENCE U
   TEXT_ENGLISH "U"
   TEXT_GERMAN "U"
}
INDEX 60
{
   REFERENCE V
   TEXT_ENGLISH "V"
   TEXT_GERMAN "V"
}
INDEX 61
{
   REFERENCE W
   TEXT_ENGLISH "W"
   TEXT_GERMAN "W"
}
INDEX 62
{
   REFERENCE X
   TEXT_ENGLISH "X"
   TEXT_GERMAN "X"
}
INDEX 63
{
   REFERENCE Y
   TEXT_ENGLISH "Y"
   TEXT_GERMAN "Y"
}
INDEX 64
{
   REFERENCE Z
   TEXT_ENGLISH "Z"
   TEXT_GERMAN "Z"
}
INDEX 65
{
   REFERENCE KP_INS
   TEXT_ENGLISH "KP_INS"
   TEXT_GERMAN "EINFG (ZIFFERNBL.)"
   TEXT_FRENCH "PN_Inser"
}
INDEX 66
{
   REFERENCE KP_END
   TEXT_ENGLISH "KP_END"
   TEXT_GERMAN "ENDE (ZIFFERNBL.)"
   TEXT_FRENCH "PN_Fin"
}
INDEX 67
{
   REFERENCE KP_DOWNARROW
   TEXT_ENGLISH "KP_DOWNARROW"
   TEXT_GERMAN "PFEILT. UNTEN (ZB)"
   TEXT_FRENCH "PN_BAS"
}
INDEX 68
{
   REFERENCE KP_PGDN
   TEXT_ENGLISH "KP_PGDN"
   TEXT_GERMAN "BILD-AB (ZIFFERNBL.)"
   TEXT_FRENCH "PN_PGBAS"
}
INDEX 69
{
   REFERENCE KP_LEFTARROW
   TEXT_ENGLISH "KP_LEFTARROW"
   TEXT_GERMAN "PFEILT. LINKS (ZB)"
   TEXT_FRENCH "PN_GAUCHE"
}
INDEX 70
{
   REFERENCE KP_5
   TEXT_ENGLISH "KP_5"
   TEXT_GERMAN "5 (ZIFFERNBLOCK)"
   TEXT_FRENCH "PN_5"
}
INDEX 71
{
   REFERENCE KP_RIGHTARROW
   TEXT_ENGLISH "KP_RIGHTARROW"
   TEXT_GERMAN "PFEILT. RECHTS (ZB)"
   TEXT_FRENCH "PN_DROITE"
}
INDEX 72
{
   REFERENCE KP_HOME
   TEXT_ENGLISH "KP_HOME"
   TEXT_GERMAN "POS 1 (ZB)"
   TEXT_FRENCH "PN_ORIGINE"
}
INDEX 73
{
   REFERENCE KP_UPARROW
   TEXT_ENGLISH "KP_UPARROW"
   TEXT_GERMAN "PFEILT. AUFWÄRTS (ZB)"
   TEXT_FRENCH "PN_HAUT"
}
INDEX 74
{
   REFERENCE KP_PGUP
   TEXT_ENGLISH "KP_PGUP"
   TEXT_GERMAN "BILD-AUF (ZIFFERNBL.)"
   TEXT_FRENCH "PN_PGBAS"
}
INDEX 75
{
   REFERENCE KP_STAR
   TEXT_ENGLISH "KP_STAR"
   TEXT_GERMAN "STERN (ZIFFERNBLOCK)"
   TEXT_FRENCH "PN_*"
}
INDEX 76
{
   REFERENCE KP_PLUS
   TEXT_ENGLISH "KP_PLUS"
   TEXT_GERMAN "PLUS (ZIFFERNBLOCK)"
   TEXT_FRENCH "PN_PLUS"
}
INDEX 77
{
   REFERENCE KP_MINUS
   TEXT_ENGLISH "KP_MINUS"
   TEXT_GERMAN "MINUS (ZIFFERNBL.)"
   TEXT_FRENCH "PN_MOINS"
}
INDEX 78
{
   REFERENCE KP_DEL
   TEXT_ENGLISH "KP_DEL"
   TEXT_GERMAN "ENTF (ZIFFERNBL.)"
   TEXT_FRENCH "PN_Suppr"
}
INDEX 79
{
   REFERENCE KP_FSLASH
   TEXT_ENGLISH "KP_FSLASH"
   TEXT_GERMAN "/ (ZIFFERNBLOCK)"
   TEXT_FRENCH "PN_SLASH"
}
INDEX 80
{
   REFERENCE MOUSE1DBL
   TEXT_ENGLISH "MOUSE1DBL"
   TEXT_GERMAN "MAUS1DBL"
   TEXT_FRENCH "DBLSOURIS1"
}
INDEX 81
{
   REFERENCE MOUSE2DBL
   TEXT_ENGLISH "MOUSE2DBL"
   TEXT_GERMAN "MAUS2DBL"
   TEXT_FRENCH "DBLSOURIS2"
}
INDEX 82
{
   REFERENCE MOUSE3DBL
   TEXT_ENGLISH "MOUSE3DBL"
   TEXT_GERMAN "MAUS3DBL"
   TEXT_FRENCH "DBLSOURIS3"
}
INDEX 83
{
   REFERENCE MOUSE4DBL
   TEXT_ENGLISH "MOUSE4DBL"
   TEXT_GERMAN "MAUS4DBL"
   TEXT_FRENCH "DBLSOURIS4"
}
INDEX 84
{
   REFERENCE MOUSE5DBL
   TEXT_ENGLISH "MOUSE5DBL"
   TEXT_GERMAN "MAUS5DBL"
   TEXT_FRENCH "DBLSOURIS5"
}
INDEX 85
{
   REFERENCE KP_NUMLOCK
   TEXT_ENGLISH "KP_NUMLOCK"
   TEXT_GERMAN "NUM (ZIFFERNBL.)"
   TEXT_FRENCH "PN_Verrnum"
}
INDEX 86
{
   REFERENCE KP_SCROLL
   TEXT_ENGLISH "KP_SCROLL"
   TEXT_GERMAN "ROLLEN (ZIFFERNBL.)"
   TEXT_FRENCH "Arrêt défil"
}
INDEX 87
{
   REFERENCE SEMICOLON
   TEXT_ENGLISH ";"
   TEXT_GERMAN "Ü"
   TEXT_FRENCH "$"
}
INDEX 88
{
   REFERENCE =
   TEXT_ENGLISH "="
   TEXT_GERMAN "+"
   TEXT_FRENCH "="
}
INDEX 89
{
   REFERENCE ,
   TEXT_ENGLISH ","
   TEXT_GERMAN ", (Komma)"
   TEXT_FRENCH ","
}
INDEX 90
{
   REFERENCE -
   TEXT_ENGLISH "-"
   TEXT_GERMAN "- (Minus)"
   TEXT_FRENCH ")"
}
INDEX 91
{
   REFERENCE .
   TEXT_ENGLISH "."
   TEXT_GERMAN ". (Punkt)"
   TEXT_FRENCH ";"
}
INDEX 92
{
   REFERENCE /
   TEXT_ENGLISH "/"
   TEXT_GERMAN "#"
   TEXT_FRENCH ":"
}
INDEX 93
{
   REFERENCE JOY1
   TEXT_ENGLISH "JOY1"
   TEXT_GERMAN "JOY1"
}
INDEX 94
{
   REFERENCE JOY2
   TEXT_ENGLISH "JOY2"
   TEXT_GERMAN "JOY2"
}
INDEX 95
{
   REFERENCE JOY3
   TEXT_ENGLISH "JOY3"
   TEXT_GERMAN "JOY3"
}
INDEX 96
{
   REFERENCE JOY4
   TEXT_ENGLISH "JOY4"
   TEXT_GERMAN "JOY4"
}
INDEX 97
{
   REFERENCE [
   TEXT_ENGLISH "["
   TEXT_GERMAN "ß"
   TEXT_FRENCH ")"
}
INDEX 98
{
   REFERENCE \
   TEXT_ENGLISH "\"
   TEXT_GERMAN "L. Umschaltt."
   TEXT_FRENCH "*"
}
INDEX 99
{
   REFERENCE ]
   TEXT_ENGLISH "]"
   TEXT_GERMAN "´ (Apostroph)"
   TEXT_FRENCH "^"
}
INDEX 100
{
   REFERENCE '
   TEXT_ENGLISH "'"
   TEXT_GERMAN "Ä"
   TEXT_FRENCH "!"
   TEXT_BRITISH "#"
}
INDEX 101
{
   REFERENCE `
   TEXT_ENGLISH "`"
   TEXT_GERMAN "Ö"
   TEXT_FRENCH "ù"
   TEXT_BRITISH "'"
}
INDEX 102
{
   REFERENCE AUX1
   TEXT_ENGLISH "AUX1"
}
INDEX 103
{
   REFERENCE AUX2
   TEXT_ENGLISH "AUX2"
}
INDEX 104
{
   REFERENCE AUX3
   TEXT_ENGLISH "AUX3"
   TEXT_GERMAN "<"
   TEXT_FRENCH "<"
}
INDEX 105
{
   REFERENCE AUX4
   TEXT_ENGLISH "AUX4"
}
INDEX 106
{
   REFERENCE AUX5
   TEXT_ENGLISH "AUX5"
}
INDEX 107
{
   REFERENCE AUX6
   TEXT_ENGLISH "AUX6"
}
INDEX 108
{
   REFERENCE AUX7
   TEXT_ENGLISH "AUX7"
}
INDEX 109
{
   REFERENCE AUX8
   TEXT_ENGLISH "AUX8"
}
INDEX 110
{
   REFERENCE AUX9
   TEXT_ENGLISH "AUX9"
}
INDEX 111
{
   REFERENCE AUX10
   TEXT_ENGLISH "AUX10"
}
INDEX 112
{
   REFERENCE AUX11
   TEXT_ENGLISH "AUX11"
}
INDEX 113
{
   REFERENCE AUX12
   TEXT_ENGLISH "AUX12"
}
INDEX 114
{
   REFERENCE AUX13
   TEXT_ENGLISH "AUX13"
}
INDEX 115
{
   REFERENCE AUX14
   TEXT_ENGLISH "AUX14"
}
INDEX 116
{
   REFERENCE AUX15
   TEXT_ENGLISH "AUX15"
}
INDEX 117
{
   REFERENCE AUX16
   TEXT_ENGLISH "AUX16"
}
INDEX 118
{
   REFERENCE AUX17
   TEXT_ENGLISH "AUX17"
}
INDEX 119
{
   REFERENCE AUX18
   TEXT_ENGLISH "AUX18"
}
INDEX 120
{
   REFERENCE AUX19
   TEXT_ENGLISH "AUX19"
}
INDEX 121
{
   REFERENCE AUX20
   TEXT_ENGLISH "AUX20"
}
INDEX 122
{
   REFERENCE AUX21
   TEXT_ENGLISH "AUX21"
}
INDEX 123
{
   REFERENCE AUX22
   TEXT_ENGLISH "AUX22"
}
INDEX 124
{
   REFERENCE AUX23
   TEXT_ENGLISH "AUX23"
}
INDEX 125
{
   REFERENCE AUX24
   TEXT_ENGLISH "AUX24"
}
INDEX 126
{
   REFERENCE AUX25
   TEXT_ENGLISH "AUX26"
}
INDEX 127
{
   REFERENCE AUX27
   TEXT_ENGLISH "AUX27"
}
INDEX 128
{
   REFERENCE AUX28
   TEXT_ENGLISH "AUX28"
}
INDEX 129
{
   REFERENCE AUX29
   TEXT_ENGLISH "AUX29"
}
INDEX 130
{
   REFERENCE AUX30
   TEXT_ENGLISH "AUX30"
}
INDEX 131
{
   REFERENCE AUX31
   TEXT_ENGLISH "AUX31"
}
INDEX 132
{
   REFERENCE AUX32
   TEXT_ENGLISH "AUX32"
}
INDEX 133
{
   REFERENCE UPARROW
   TEXT_ENGLISH "UPARROW"
   TEXT_GERMAN "PFEILT. AUFWÄRTS"
   TEXT_FRENCH "HAUT"
}
INDEX 134
{
   REFERENCE ENTER
   TEXT_ENGLISH "ENTER"
   TEXT_GERMAN "EINGABETASTE"
   TEXT_FRENCH "ENTREE"
}
INDEX 135
{
   REFERENCE KP_ENTER
   TEXT_ENGLISH "KP_ENTER"
   TEXT_GERMAN "ENTER (ZIFFERNBL.)"
   TEXT_FRENCH "PN_Entr"
}
INDEX 136
{
   REFERENCE AUX25
   TEXT_ENGLISH "AUX25"
}
INDEX 137
{
   REFERENCE !
   TEXT_ENGLISH "!"
   TEXT_GERMAN "!"
   TEXT_FRENCH "!"
   TEXT_BRITISH "!"
}
