VERSION 1
ID 248
REFERENCE MENU_AUDIO
DESCRIPTION "text for the audio menu (excluding tips)"
COUNT 14
INDEX 0
{
   REFERENCE DYNAMIC
   TEXT_ENGLISH "DYNAMIC SOUND SETTINGS"
   TEXT_GERMAN "LAUTSTÄRKEREGELUNG"
   TEXT_FRENCH "PARAMETRES SON DYNAMIQUES"
}
INDEX 1
{
   REFERENCE FX_VOLUME
   TEXT_ENGLISH "Effects Volume"
   TEXT_GERMAN "SFX-Lautstärke"
   TEXT_FRENCH "Volume des effets"
}
INDEX 2
{
   REFERENCE MUSIC_VOLUME
   TEXT_ENGLISH "Music Volume"
   TEXT_GERMAN "Musik-Lautstärke"
   TEXT_FRENCH "Volume musique"
}
INDEX 3
{
   REFERENCE SOUND_SYSTEM
   TEXT_ENGLISH "SOUND SYSTEM SETTINGS"
   TEXT_GERMAN "SOUNDEINSTELLUNGEN"
   TEXT_FRENCH "PARAMETRES SYSTEME AUDIO"
}
INDEX 4
{
   REFERENCE DRIVER
   TEXT_ENGLISH "Auto detect,Default,EAX,A3D"
   TEXT_GERMAN "Autom. Erkennung,Standard,EAX,A3D"
   TEXT_FRENCH "Détection auto,Par défaut,EAX,A3D"
}
INDEX 5
{
   REFERENCE OFF_ON
   TEXT_ENGLISH "Off,On"
   TEXT_GERMAN "Aus,Ein"
   TEXT_FRENCH "Off,On"
}
INDEX 6
{
   REFERENCE DIS_EN
   TEXT_ENGLISH "Disabled,Enabled"
   TEXT_GERMAN "Deaktiviert,Aktiviert"
   TEXT_FRENCH "Désactivée,Activée"
}
INDEX 7
{
   REFERENCE SOUND_DLL
   TEXT_ENGLISH "Sound Driver"
   TEXT_GERMAN "Soundtreiber"
   TEXT_FRENCH "Pilote son"
}
INDEX 8
{
   REFERENCE TITLE
   TEXT_ENGLISH "AUDIO SETTINGS"
   TEXT_GERMAN "AUDIO-EINSTELLUNGEN"
   TEXT_FRENCH "PARAMETRES AUDIO"
}
INDEX 10
{
   REFERENCE SOUND_FREQ
   TEXT_ENGLISH "Sound Frequency"
   TEXT_GERMAN "Soundfrequenz"
   TEXT_FRENCH "Fréquence sonore"
}
INDEX 13
{
   REFERENCE SOUND_QUALITY
   TEXT_ENGLISH "Sample Rate"
   TEXT_GERMAN "Sample-Rate"
   TEXT_FRENCH "Qualité audio"
}
INDEX 18
{
   REFERENCE DS_BUFFER
   TEXT_ENGLISH "Exclusive DS Buffer"
   TEXT_GERMAN "Exklusiver DS-Buffer"
   TEXT_FRENCH "Buffer DS exclusif"
}
INDEX 19
{
   REFERENCE DYNA_MUSIC
   TEXT_ENGLISH "Dynamic Music"
   TEXT_GERMAN "Musikeinstellungen"
   TEXT_FRENCH "Musique dynamique"
}
INDEX 20
{
   REFERENCE TICKER
   TEXT_ENGLISH "*** CLICK AN OPTION TO ADJUST AND PRESS APPLY CHANGES TO SET ***"
   TEXT_GERMAN "*** KLICKEN SIE AUF EINE OPTION, UM SIE ZU ÄNDERN, UND DANN AUF  ÄNDERUNGEN ÜBERNEHMEN ***"
   TEXT_FRENCH "*** CLIQUEZ SUR UNE OPTION POUR LA REGLER *** CLIQUEZ SUR APPLIQUER MODIFICATIONS POUR VALIDER ***"
}
