VERSION 1
ID 244
REFERENCE MENU_GAME
DESCRIPTION "game menu text"
COUNT 39
INDEX 0
{
   REFERENCE DIFFICULTY
   TEXT_ENGLISH "DIFFICULTY"
   TEXT_GERMAN "SCHWIERIGKEIT"
   TEXT_FRENCH "DIFFICULTE"
}
INDEX 1
{
   REFERENCE MAIN
   TEXT_ENGLISH "*** START A NEW GAME OR TRAIN ON THE PRACTICE LEVEL ***"
   TEXT_GERMAN "*** STARTEN SIE EIN NEUES SPIEL ODER ÜBEN SIE IM TRAININGSLEVEL ***"
   TEXT_FRENCH "*** DEMARREZ UNE NOUVELLE PARTIE OU ENTRAINEZ-VOUS SUR LE NIVEAU DIDACTICIEL ***"
}
INDEX 2
{
   REFERENCE START
   TEXT_ENGLISH "START GAME"
   TEXT_GERMAN "SPIEL STARTEN"
   TEXT_FRENCH "DEMARRER PARTIE"
}
INDEX 3
{
   REFERENCE TCUSTOM
   TEXT_ENGLISH "*** DEFINE YOUR CUSTOM LEVEL OF DIFFICULTY *** "
   TEXT_GERMAN "*** LEGEN SIE DEN EINSTELLBAREN SCHWIERIGKEITSGRAD FEST *** "
   TEXT_FRENCH "*** DEFINIR VOTRE NIVEAU DE DIFFICULTE PERSONNALISE *** "
}
INDEX 4
{
   REFERENCE TUT
   TEXT_ENGLISH "PLAY TUTORIAL"
   TEXT_GERMAN "TRAINING SPIELEN"
   TEXT_FRENCH "JOUER DIDACTICIEL"
}
INDEX 5
{
   REFERENCE OFF_ON
   TEXT_ENGLISH "Off,On"
   TEXT_GERMAN "Aus,Ein"
   TEXT_FRENCH "Off,On"
}
INDEX 6
{
   REFERENCE CHANGE
   TEXT_ENGLISH "Change codename"
   TEXT_GERMAN "Codenamen ändern"
   TEXT_FRENCH "Changer nom de code"
}
INDEX 7
{
   REFERENCE CREDITS
   TEXT_ENGLISH "CREDITS"
   TEXT_GERMAN "CREDITS"
   TEXT_FRENCH "CREDITS"
}
INDEX 8
{
   REFERENCE NEW_SAVE
   TEXT_ENGLISH "NEW SAVEGAME"
   TEXT_GERMAN "NEUER SPIELSTAND"
   TEXT_FRENCH "NOUVEL ENREGISTREMENT"
}
INDEX 9
{
   REFERENCE TICKER
   TEXT_ENGLISH "*** SELECT DIFFICULTY SETTING TO START GAME ***"
   TEXT_GERMAN "*** WÄHLEN SIE EINEN SCHWIERIGKEITSGRAD, UM DAS SPIEL ZU STARTEN ***"
   TEXT_FRENCH "*** SELECTIONNER LE NIVEAU DE DIFFICULTE POUR DEMARRER LA PARTIE ***"
}
INDEX 10
{
   REFERENCE SAVES
   TEXT_ENGLISH "None,Few,Some,Many,Unlimited"
   TEXT_GERMAN "Keine,Wenige,Ein paar,Viele,Unbeschränkt"
   TEXT_FRENCH "Aucun,Peu,Quelques,Beaucoup,Illimités"
}
INDEX 11
{
   REFERENCE SAVENUM
   TEXT_ENGLISH "Number of saves"
   TEXT_GERMAN "Anzahl an Speichermöglichkeiten"
   TEXT_FRENCH "Nombre d'enregistrements"
}
INDEX 12
{
   REFERENCE SPAWNING
   TEXT_ENGLISH "None,Light,Standard,Heavy,Ridiculous"
   TEXT_GERMAN "Aus,Leicht,Standard,Hart,Extrem"
   TEXT_FRENCH "Aucun,Léger,Standard,Lourd,Ridicule"
}
INDEX 13
{
   REFERENCE SPAWNNUM
   TEXT_ENGLISH "Type of spawning"
   TEXT_GERMAN "Art des Wiedereinstiegs"
   TEXT_FRENCH "Type de régénérescence"
}
INDEX 14
{
   REFERENCE TOUGH
   TEXT_ENGLISH "Non-threatening,Uncertain,Standard,Aggressive,Bloodthirsty"
   TEXT_GERMAN "Lammfromm,Unerfahren,Standard,Aggressiv,Blutrünstig"
   TEXT_FRENCH "Inoffensif,Indéfini,Standard,Agressif,Monstre"
}
INDEX 15
{
   REFERENCE TOUGHNUM
   TEXT_ENGLISH "Enemy toughness"
   TEXT_GERMAN "Gegnerstärke"
   TEXT_FRENCH "Caractère ennemi"
}
INDEX 16
{
   REFERENCE CA
   TEXT_ENGLISH "Cheats Available"
   TEXT_GERMAN "Vorhandene Cheats"
   TEXT_FRENCH "Cheats disponibles"
}
INDEX 17
{
   REFERENCE SDIFF
   TEXT_ENGLISH "SELECT DIFFICULTY LEVEL"
   TEXT_GERMAN "WÄHLEN SIE EINEN SCHWIERIGKEITSGRAD"
   TEXT_FRENCH "SELECTIONNER NIVEAU DE DIFFICULTE"
}
INDEX 18
{
   REFERENCE DIFF0
   TEXT_ENGLISH "Effortless"
   TEXT_GERMAN "Mühelos"
   TEXT_FRENCH "Super facile"
}
INDEX 19
{
   REFERENCE DIFF1
   TEXT_ENGLISH "Easy"
   TEXT_GERMAN "Leicht"
   TEXT_FRENCH "Facile"
}
INDEX 20
{
   REFERENCE DIFF2
   TEXT_ENGLISH "Medium"
   TEXT_GERMAN "Mittel"
   TEXT_FRENCH "Moyen"
}
INDEX 21
{
   REFERENCE DIFF3
   TEXT_ENGLISH "Challenging"
   TEXT_GERMAN "Hart"
   TEXT_FRENCH "Difficile"
}
INDEX 22
{
   REFERENCE DIFF4
   TEXT_ENGLISH "Unfair"
   TEXT_GERMAN "Unfair"
   TEXT_FRENCH "Injuste"
}
INDEX 23
{
   REFERENCE DIFF5
   TEXT_ENGLISH "Custom"
   TEXT_GERMAN "Einstellen"
   TEXT_FRENCH "Personnalisé"
}
INDEX 24
{
   REFERENCE ENCUM
   TEXT_ENGLISH "Unlimited,Numerous,Standard,Limited"
   TEXT_GERMAN "Unbeschränkt,Zahlreich,Standard,Beschränkt"
   TEXT_FRENCH "Illimités,Nombreux,Standard,Limités"
}
INDEX 25
{
   REFERENCE NAME_CHANGE
   TEXT_ENGLISH "CHANGE YOUR USER NAME"
   TEXT_GERMAN "ÄNDERN SIE IHREN BENUTZERNAMEN"
   TEXT_FRENCH "CHANGER VOTRE NOM D'UTILISATEUR"
}
INDEX 26
{
   REFERENCE CUSTOM
   TEXT_ENGLISH "CUSTOM SETTINGS"
   TEXT_GERMAN "EINSTELLUNGEN ANPASSEN"
   TEXT_FRENCH "PARAMETRES PERSONNALISES"
}
INDEX 27
{
   REFERENCE BEGIN_GAME
   TEXT_ENGLISH "BEGIN A NEW GAME"
   TEXT_GERMAN "NEUES SPIEL STARTEN"
   TEXT_FRENCH "DEMARRER NOUVELLE PARTIE"
}
INDEX 28
{
   REFERENCE LOAD_GAME
   TEXT_ENGLISH "LOAD GAME FROM HARD DRIVE"
   TEXT_GERMAN "SPIEL VON FESTPLATTE LADEN"
   TEXT_FRENCH "CHARGER PARTIE DU DISQUE DUR"
}
INDEX 29
{
   REFERENCE SAVE_GAME
   TEXT_ENGLISH "SAVE GAME TO HARD DRIVE"
   TEXT_GERMAN "SPIEL AUF FESTPLATTE SPEICHERN"
   TEXT_FRENCH "ENREGISTRER PARTIE SUR DISQUE DUR"
}
INDEX 30
{
   REFERENCE ALTER_GAME
   TEXT_ENGLISH "ALTER GAME SETTINGS"
   TEXT_GERMAN "SPIELEINSTELLUNGEN ÄNDERN"
   TEXT_FRENCH "MODIFIER PARAMETRES DE JEU"
}
INDEX 31
{
   REFERENCE MAIL_TICKER
   TEXT_ENGLISH "*** EYES ONLY: CLASSIFIED MATERIAL ***"
   TEXT_GERMAN "*** VERTRAULICH: STRENG GEHEIMES MATERIAL ***"
   TEXT_FRENCH "*** VISUEL UNIQUEMENT : INFOS CONFIDENTIELLES ***"
}
INDEX 32
{
   REFERENCE TICKER1
   TEXT_ENGLISH "*** CLICK ON IMAGE TO LOAD SAVEGAME *** USE A RIGHT MOUSE CLICK TO DELETE AN EXISTING SAVEGAME *** YOU CANNOT DELETE AUTOSAVES! ***"
   TEXT_GERMAN "*** KLICKEN SIE AUF EIN BILD, UM DEN SPIELSTAND ZU LADEN *** MIT EINEM RECHTEN MAUSKLICK KÖNNEN SIE EINEN VORHANDENEN SPIELSTAND LÖSCHEN *** SIE KÖNNEN KEINE AUTOSAVES LÖSCHEN!"
   TEXT_FRENCH "*** CLIQUEZ SUR UNE IMAGE POUR CHARGER UN ENREGISTREMENT *** CLIQUEZ-DROIT POUR SUPPRIMER UN ENREGISTREMENT EXISTANT *** IMPOSSIBLE DE SUPPRIMER LES ENREGISTREMENTS AUTO ! ***"
}
INDEX 33
{
   REFERENCE TICKER2
   TEXT_ENGLISH "*** CLICK ON AN IMAGE TO SAVE IN THAT SLOT OR CLICK 'NEW SAVEGAME' TO CREATE A NEW SLOT *** USE A RIGHT MOUSE CLICK TO DELETE AN EXISTING SAVEGAME ***"
   TEXT_GERMAN "*** KLICKEN SIE AUF EIN BILD, UM IN DEM JEWEILIGEN SPEICHERPLATZ ZU SPEICHERN, ODER KLICKEN SIE AUF 'NEUER SPIELSTAND', UM EINEN NEUEN SPEICHERPLATZ EINZURICHTEN *** MIT EINEM RECHTEN MAUSKLICK KÖNNEN SIE VORHANDENE SPIELSTÄNDE LÖSCHEN"
   TEXT_FRENCH "*** CLIQUEZ SUR UNE IMAGE POUR ENREGISTRER DANS LE LOGEMENT OU CLIQUEZ SUR 'NOUVEL ENREGISTREMENT' POUR CREER UN LOGEMENT *** CLIQUEZ-DROIT POUR SUPPRIMER UN ENREGISTREMENT EXISTANT ***"
}
INDEX 34
{
   REFERENCE ENCUMNUM
   TEXT_ENGLISH "Carrying capacity"
   TEXT_GERMAN "Tragkapazität"
   TEXT_FRENCH "Capacité transport"
}
INDEX 35
{
   REFERENCE CUSTOM_DEFINED1
   TEXT_ENGLISH "Difficulty levels adjust the following settings:"
   TEXT_GERMAN "Die Schwierigkeitsgrade passen folgende Einstellungen an:"
   TEXT_FRENCH "Selon la difficulté, les paramètres suivants sont modifiés :"
}
INDEX 36
{
   REFERENCE CUSTOM_DEFINED2
   TEXT_ENGLISH "Choose custom to adjust settings to your preferences"
   TEXT_GERMAN "Wählen Sie 'Einstellen', um die Einstellungen nach Ihrem Belieben anzupassen."
   TEXT_FRENCH "Choisissez Personnalisé pour régler selon vos préférences"
}
INDEX 37
{
   REFERENCE LOADGAME
   TEXT_ENGLISH "LOAD GAME"
   TEXT_GERMAN "SPIEL LADEN"
   TEXT_FRENCH "CHARGER PARTIE"
}
INDEX 38
{
   REFERENCE SAVEGAME
   TEXT_ENGLISH "SAVE GAME"
   TEXT_GERMAN "SPIEL SPEICHERN"
   TEXT_FRENCH "ENREGISTRER PARTIE"
}
