VERSION 1
ID 203
REFERENCE MENU_VIDEO
DESCRIPTION "Video menu"
COUNT 28
INDEX 0
{
   REFERENCE DYNAMIC
   TEXT_ENGLISH "DYNAMIC VIDEO SETTINGS"
   TEXT_GERMAN "GRAFIKEINSTELLUNGEN"
   TEXT_FRENCH "PARAMETRES VIDEO DYNAMIQUES"
}
INDEX 1
{
   REFERENCE TM
   TEXT_ENGLISH "None,Bilinear,Mipped Bilinear,Trilinear"
   TEXT_GERMAN "Nichts,Bilinear,Mipped Bilinear,Trilinear"
   TEXT_FRENCH "Aucun,Bilinéaire,Mip bilinéaire,Trilinéaire"
}
INDEX 2
{
   REFERENCE DRIVER
   TEXT_ENGLISH "Default OpenGL,3DFx OpenGL"
   TEXT_GERMAN "Standard-Open GL,3DFX-Open GL"
   TEXT_FRENCH "OpenGL par défaut,OpenGl 3DFX"
}
INDEX 3
{
   REFERENCE NOYES
   TEXT_ENGLISH "No,Yes"
   TEXT_GERMAN "Nein,Ja"
   TEXT_FRENCH "Non,Oui"
}
INDEX 4
{
   REFERENCE MIP
   TEXT_ENGLISH "Very Low, Low,Medium,High"
   TEXT_GERMAN "Sehr niedrig,Niedrig,Mittel,Hoch"
   TEXT_FRENCH "Très faible,Faible,Moyenne,Elevée"
}
INDEX 5
{
   REFERENCE VIDEO_SETTINGS
   TEXT_ENGLISH "VIDEO SYSTEM SETTINGS"
   TEXT_GERMAN "GRAFIKKARTEN-EINSTELLUNGEN"
   TEXT_FRENCH "PARAMETRES SYSTEME VIDEO"
}
INDEX 6
{
   REFERENCE ISF
   TEXT_ENGLISH "Default,S3 Compressed,DXT Compressed,Low,Medium,High"
   TEXT_GERMAN "Standard,S3-komprimiert,DXT-komprimiert,Niedrig,Mittel,Hoch"
   TEXT_FRENCH "Par défaut,Compressé S3,Compressé DXT,Faible,Moyen,Elevé"
}
INDEX 7
{
   REFERENCE TMODE
   TEXT_ENGLISH "Texture Mode"
   TEXT_GERMAN "Texturmodus"
   TEXT_FRENCH "Mode Texture"
}
INDEX 8
{
   REFERENCE VIDEO_DRIVER
   TEXT_ENGLISH "Video Driver"
   TEXT_GERMAN "Grafiktreiber"
   TEXT_FRENCH "Pilote vidéo"
}
INDEX 9
{
   REFERENCE RESOLUTION
   TEXT_ENGLISH "Resolution"
   TEXT_GERMAN "Auflösung"
   TEXT_FRENCH "Résolution"
}
INDEX 10
{
   REFERENCE SOLID_TEXT
   TEXT_ENGLISH "Texture Format"
   TEXT_GERMAN "Texturformat"
   TEXT_FRENCH "Format Texture"
}
INDEX 11
{
   REFERENCE TITLE
   TEXT_ENGLISH "DISPLAY SETTINGS"
   TEXT_GERMAN "ANZEIGE"
   TEXT_FRENCH "PARAMETRES AFFICHAGE"
}
INDEX 12
{
   REFERENCE FULLSCREEN
   TEXT_ENGLISH "Full Screen"
   TEXT_GERMAN "Vollbild"
   TEXT_FRENCH "Plein écran"
}
INDEX 13
{
   REFERENCE ALTERNATE_TEXT
   TEXT_ENGLISH "Alternate Simple Textures"
   TEXT_GERMAN "Wechselnde einfache Texturen"
   TEXT_FRENCH "Autres textures simples"
}
INDEX 14
{
   REFERENCE AST
   TEXT_ENGLISH "Auto,16 Bit,32 Bit"
   TEXT_GERMAN "Auto,16 Bit,32 Bit"
   TEXT_FRENCH "Auto,16 bits,32 bits"
}
INDEX 15
{
   REFERENCE BD
   TEXT_ENGLISH "Bitdepth"
   TEXT_GERMAN "Bit-Tiefe"
   TEXT_FRENCH "Nombre de couleurs"
}
INDEX 16
{
   REFERENCE GFXDET
   TEXT_ENGLISH "GRAPHICS DETAILS"
   TEXT_GERMAN "GRAFIKDETAILS"
   TEXT_FRENCH "DETAILS GRAPHIQUES"
}
INDEX 17
{
   REFERENCE ISF2
   TEXT_ENGLISH "Default,Low,Medium,High"
   TEXT_GERMAN "Standard,Niedrig,Mittel,Hoch"
   TEXT_FRENCH "Par défaut,Faible,Moyen,Elevé"
}
INDEX 18
{
   REFERENCE TEXTURE_QUALITY
   TEXT_ENGLISH "Texture Quality"
   TEXT_GERMAN "Texturqualität"
   TEXT_FRENCH "Qualité des textures"
}
INDEX 19
{
   REFERENCE SKIN_TEXT_QUAL
   TEXT_ENGLISH "Skin Texture Quality"
   TEXT_GERMAN "Skin-Texturqualität"
   TEXT_FRENCH "Qualité texture d'habillage"
}
INDEX 22
{
   REFERENCE TRANS_TEXT
   TEXT_ENGLISH "Translucent Texture Format"
   TEXT_GERMAN "Transparentes Texturformat"
   TEXT_FRENCH "Format de texture translucide"
}
INDEX 23
{
   REFERENCE GAMMA
   TEXT_ENGLISH "Gamma"
   TEXT_GERMAN "Gamma"
   TEXT_FRENCH "Gamma"
}
INDEX 24
{
   REFERENCE CONTRAST
   TEXT_ENGLISH "Contrast"
   TEXT_GERMAN "Kontrast"
   TEXT_FRENCH "Contraste"
}
INDEX 25
{
   REFERENCE BRIGHTNESS
   TEXT_ENGLISH "Brightness"
   TEXT_GERMAN "Helligkeit"
   TEXT_FRENCH "Luminosité"
}
INDEX 26
{
   REFERENCE LIGHT_INTENSITY
   TEXT_ENGLISH "Intensity"
   TEXT_GERMAN "Lichtstärke"
   TEXT_FRENCH "Intensité"
}
INDEX 27
{
   REFERENCE APPLY_DEFAULTS
   TEXT_ENGLISH "APPLY DEFAULTS"
   TEXT_GERMAN "STANDARD WIEDERHERSTELLEN"
   TEXT_FRENCH "Paramètres par défaut"
}
INDEX 28
{
   REFERENCE APPLY_CHANGES
   TEXT_ENGLISH "APPLY CHANGES"
   TEXT_GERMAN "ÄNDERUNGEN ÜBERNEHMEN"
   TEXT_FRENCH "Appliquer modifications"
}
INDEX 29
{
   REFERENCE TICKER
   TEXT_ENGLISH "*** MOVE SLIDER BARS TO CHANGE TO THE DESIRED SETTINGS *** WE RECOMMEND THAT YOU SET YOUR MACHINE SO THAT FOUR IS THE LAST VISIBLE BUTTON *** CLICK 'APPLY CHANGES' FOR SETTINGS TO TAKE EFFECT ***"
   TEXT_GERMAN "*** BEWEGEN SIE DIE REGLER, UM ZU IHREN GEWÜNSCHTEN EINSTELLUNGEN ZU WECHSELN *** SIE SOLLTEN IHREN RECHNER SO EINSTELLEN, DASS VIER DER LETZTE SICHTBARE BUTTON IST *** KLICKEN SIE AUF 'ÄNDERUNGEN ÜBERNEHMEN', UM DIE EINSTELLUNGEN ZU AKTIVIEREN ***"
   TEXT_FRENCH "*** REGLEZ LES PARAMETRES VOULUS A L'AIDE DES CURSEURS *** CONSEIL : DEFINISSEZ VOTRE MACHINE DE SORTE QUE LA DERNIERE GRADUATION VISIBLE SOIT LE CHIFFRE QUATRE *** CLIQUEZ SUR 'APPLIQUER MODIFICATIONS' POUR QU'ELLES SOIENT PRISES EN COMPTE ***"
}
