VERSION 1
ID 205
REFERENCE MENU_OUTFIT
DESCRIPTION "Outfitting menu"
COUNT 7
INDEX 0
{
   REFERENCE INVEN
   TEXT_ENGLISH "I  N  V  E  N  T  O  R  Y"
   TEXT_GERMAN "A  U  S  R  Ü  S  T  U  N  G"
   TEXT_FRENCH "I  N  V  E  N  T  A  I  R  E "
}
INDEX 1
{
   REFERENCE DEPLOY
   TEXT_ENGLISH "DEPLOY"
   TEXT_GERMAN "EINSATZ"
   TEXT_FRENCH "ACTION"
}
INDEX 2
{
   REFERENCE TICKER
   TEXT_ENGLISH "*** SELECT APPROPRIATE WEAPONS AND ITEMS ***"
   TEXT_GERMAN "*** WÄHLEN SIE GEEIGNETE WAFFEN UND GEGENSTÄNDE ***"
   TEXT_FRENCH "*** SELECTIONNEZ LES ARMES ET ACCESSOIRES APPROPRIES ***"
}
INDEX 3
{
   REFERENCE TIP
   TEXT_ENGLISH "OUTFIT YOURSELF"
   TEXT_GERMAN "RÜSTEN SIE SICH AUS"
   TEXT_FRENCH "EQUIPEMENT"
}
INDEX 4
{
   REFERENCE RETURN_MAIL
   TEXT_ENGLISH "RETURN TO MAIL"
   TEXT_GERMAN "ZURÜCK ZUR MAIL"
   TEXT_FRENCH "REVENIR AU COURRIER"
}
INDEX 5
{
   REFERENCE DEPLOY1
   TEXT_ENGLISH "Confirm"
   TEXT_GERMAN "Einsatz"
   TEXT_FRENCH "Confirmer"
}
INDEX 6
{
   REFERENCE DEPLOY2
   TEXT_ENGLISH "Deployment"
   TEXT_GERMAN "bestätigen"
   TEXT_FRENCH "Action"
}
