VERSION 1
ID 200
REFERENCE MENU_GENERIC
DESCRIPTION "Generic Menu Text"
COUNT 77
INDEX 0
{
   REFERENCE MAIN_TICKER
   NOTES "The ticker file when you first enter the game"
   TEXT_ENGLISH "*** WELCOME TO SOLDIER OF FORTUNE PLATINUM EDITION ***\n!!THIS GAME IS RATED 'M' FOR MATURE AUDIENCES ONLY!!\n*** TO USE THE VIOLENCE LOCK FEATURE TO REMOVE OBJECTIONABLE MATERIAL, CLICK THE 'LOCK' ICON ***\n!!TO BEGIN A NEW GAME, CLICK THE 'GAME' ICON!!\n*** TO CHANGE VIDEO, CONTROL, AND AUDIO OPTIONS, PRESS THE 'OPTIONS' ICON *** \n!! TO REPORT ANY PROBLEMS USE THE MESSAGEBOARD AT HTTP://SOF.RAVENSOFT.COM !!\n"
   TEXT_GERMAN "*** HERZLICH WILLKOMMEN ZU SOLDIER OF FORTUNE ***\n!!UM EIN NEUES SPIEL ZU STARTEN, KLICKEN SIE AUF DAS 'SPIEL'-ICON!!\n*** UM DIE GRAFIK-, STEUERUNGS- UND AUDIO-OPTIONEN ZU ÄNDERN, KLICKEN SIE AUF DAS 'OPTIONEN'-ICON. ***\n!!WOLLEN SIE UNS AUF ETWAIGE PROBLEME AUFMERKSAM MACHEN, TUN SIE DIES BITTE ÜBER DAS MESSAGEBOARD UNTER HTTP://SOF.RAVENSOFT.COM!!***\n"
   TEXT_FRENCH "*** BIENVENUE A SOLDIER OF FORTUNE ***\n!! CE JEU EST DESTINE A UN PUBLIC ADULTE !!\n*** POUR UTILISER LA FONCTION DE VERROU PARENTAL QUI PERMET D'ELIMINER CERTAINS ELEMENTS DU JEU, CLIQUEZ SUR L'ICONE 'VERROU' ***\n!! POUR DEMARRER UNE NOUVELLE PARTIE, CLIQUEZ SUR L'ICONE 'PARTIE' !!\n*** POUR CHANGER LES PARAMETRES VIDEO, AUDIO ET DE CONTROLE, CLIQUEZ SUR L'ICONE 'OPTIONS' ***\n*** FAITES-NOUS PART DE VOS PROBLEMES SUR LE SITE HTTP://SOF.RAVENSOFT.COM ***\n"
}
INDEX 1
{
   REFERENCE MAIL_TICKER
   TEXT_ENGLISH "*** CLICK ON THE MAIL ICON TO RECEIVE MISSION ORDERS ***"
   TEXT_GERMAN "*** KLICKEN SIE AUF DAS BRIEF-ICON, UM MISSIONSANWEISUNGEN ZU ERHALTEN. ***"
   TEXT_FRENCH "*** CLIQUEZ SUR L'ICONE COURRIER POUR RECEVOIR VOS ORDRES DE MISSION ***"
}
INDEX 2
{
   REFERENCE ALTER_QUESTION1
   TEXT_ENGLISH "Do you want to"
   TEXT_GERMAN "Möchten Sie"
   TEXT_FRENCH "Appliquer"
}
INDEX 3
{
   REFERENCE ALTER_QUESTION2
   TEXT_ENGLISH "apply your changes?"
   TEXT_GERMAN "Änderungen übern.?"
   TEXT_FRENCH "vos modifications ?"
}
INDEX 4
{
   REFERENCE YES
   TEXT_ENGLISH "Yes"
   TEXT_GERMAN "Ja"
   TEXT_FRENCH "Oui"
}
INDEX 5
{
   REFERENCE NO
   TEXT_ENGLISH "No"
   TEXT_GERMAN "Nein"
   TEXT_FRENCH "Non"
}
INDEX 6
{
   REFERENCE ALTER_APPLIED1
   TEXT_ENGLISH "Changes have"
   TEXT_GERMAN "Die Änderungen"
   TEXT_FRENCH "Les modifications"
}
INDEX 7
{
   REFERENCE ALTER_APPLIED2
   TEXT_ENGLISH "been applied"
   TEXT_GERMAN "wurden übernommen."
   TEXT_FRENCH "ont été appliquées"
}
INDEX 8
{
   REFERENCE OK
   TEXT_ENGLISH "OK"
   TEXT_GERMAN "OK"
   TEXT_FRENCH "OK"
}
INDEX 9
{
   REFERENCE ALTER_DEFAULT1
   TEXT_ENGLISH "Default settings"
   TEXT_GERMAN "Standardeinstell."
   TEXT_FRENCH "Paramètres par"
}
INDEX 10
{
   REFERENCE ALTER_DEFAULT2
   TEXT_ENGLISH "have been applied"
   TEXT_GERMAN "wurden übernommen."
   TEXT_FRENCH "défaut appliqués"
}
INDEX 11
{
   REFERENCE EXIT_QUESTION1
   TEXT_ENGLISH "This will exit the"
   TEXT_GERMAN "Hiermit verlassen Sie"
   TEXT_FRENCH "Vous allez quitter"
}
INDEX 12
{
   REFERENCE EXIT_QUESTION2
   TEXT_ENGLISH "current game"
   TEXT_GERMAN "das aktuelle Spiel."
   TEXT_FRENCH "la partie en cours"
}
INDEX 13
{
   REFERENCE SURE
   TEXT_ENGLISH "Are you sure?"
   TEXT_GERMAN "Sind Sie sicher?"
   TEXT_FRENCH "En êtes-vous sûr(e) ?"
}
INDEX 14
{
   REFERENCE OVERWRITE
   TEXT_ENGLISH "Overwrite"
   TEXT_GERMAN "Überschreiben"
   TEXT_FRENCH "Ecraser"
}
INDEX 15
{
   REFERENCE QUIT
   TEXT_ENGLISH "Quit"
   TEXT_GERMAN "Beenden"
   TEXT_FRENCH "Quitter"
}
INDEX 16
{
   REFERENCE UNBOUND1
   TEXT_ENGLISH "All keys have"
   TEXT_GERMAN "Alle Tastenbeleg."
   TEXT_FRENCH "Toutes les touches"
}
INDEX 17
{
   REFERENCE UNBOUND2
   TEXT_ENGLISH "been unbound"
   TEXT_GERMAN "wurden gelöscht."
   TEXT_FRENCH "sont déprogrammées"
}
INDEX 18
{
   REFERENCE DELETE_SAVE
   TEXT_ENGLISH "Delete savegame"
   TEXT_GERMAN "Spielstand löschen"
   TEXT_FRENCH "Supprimer enregistrement"
}
INDEX 19
{
   REFERENCE LOGIN
   TEXT_ENGLISH "Login"
   TEXT_GERMAN "Einlog."
   TEXT_FRENCH "Login"
}
INDEX 20
{
   REFERENCE APPLY_CHANGES
   TEXT_ENGLISH "APPLY CHANGES"
   TEXT_GERMAN "ÄNDERUNGEN ÜBERNEHMEN"
   TEXT_FRENCH "APPLIQUER MODIFICATIONS"
}
INDEX 21
{
   REFERENCE APPLY_DEFAULTS
   TEXT_ENGLISH "APPLY DEFAULTS"
   TEXT_GERMAN "STANDARDEINST. ÜBERNEHMEN"
   TEXT_FRENCH "PARAMETRES PAR DEFAUT"
}
INDEX 22
{
   REFERENCE EMAIL_RECIP
   TEXT_ENGLISH "To"
   TEXT_GERMAN "An"
   TEXT_FRENCH "A"
}
INDEX 23
{
   REFERENCE EMAIL_CLASS
   TEXT_ENGLISH "Classification: EYES ONLY"
   TEXT_GERMAN "Einstufung: VERTRAULICH"
   TEXT_FRENCH "Classification : VISUEL UNIQUEMENT"
}
INDEX 24
{
   REFERENCE ACC1
   TEXT_ENGLISH "MISSION ACCOMPLISHED"
   TEXT_GERMAN "MISSION ERFÜLLT"
   TEXT_FRENCH "MISSION ACCOMPLIE"
}
INDEX 25
{
   REFERENCE ACC2
   TEXT_ENGLISH "WELL DONE,"
   TEXT_GERMAN "GUTE ARBEIT,"
   TEXT_FRENCH "BRAVO,"
}
INDEX 26
{
   REFERENCE DISCLAIMER1A
   TEXT_ENGLISH "WARNING: SOLDIER OF FORTUNE CONTAINS SCENES"
   TEXT_GERMAN "WARNUNG: SOLDIER OF FORTUNE ENTHÄLT"
   TEXT_FRENCH "AVERTISSEMENT :"
}
INDEX 27
{
   REFERENCE DISCLAIMER2
   TEXT_ENGLISH "VIEWER DISCRETION IS ADVISED"
   TEXT_GERMAN "BITTE BEACHTEN SIE DIESEN HINWEIS!"
   TEXT_FRENCH "CE JEU EST DESTINE A UN PUBLIC ADULTE."
}
INDEX 28
{
   REFERENCE DISCLAIMER1B
   TEXT_ENGLISH "OF GRAPHIC VIOLENCE AND IS INTENDED "
   TEXT_GERMAN "GEWALTTÄTIGE SZENEN UND IST NUR FÜR"
   TEXT_FRENCH "SOLDIER OF FORTUNE CONTIENT DES SCENES"
}
INDEX 29
{
   REFERENCE DISCLAIMER1C
   TEXT_ENGLISH "FOR MATURE AUDIENCES ONLY."
   TEXT_GERMAN "EIN ERWACHSENES PUBLIKUM GEEIGNET."
   TEXT_FRENCH "DE VIOLENCE GRAPHIQUE."
}
INDEX 30
{
   REFERENCE DIS
   TEXT_ENGLISH "Disconnected!"
   TEXT_GERMAN "Verbindung unterbrochen!"
   TEXT_FRENCH "Déconnecté !"
}
INDEX 31
{
   REFERENCE CV
   TEXT_ENGLISH "Card Vendor"
   TEXT_GERMAN "Kartenhersteller"
   TEXT_FRENCH "Fournisseur de la carte"
}
INDEX 32
{
   REFERENCE RENDERER
   TEXT_ENGLISH "Renderer"
   TEXT_GERMAN "Renderer"
   TEXT_FRENCH "Système de rendu"
}
INDEX 33
{
   REFERENCE SWR
   TEXT_ENGLISH "Software Revision"
   TEXT_GERMAN "Programm-Version"
   TEXT_FRENCH "Version du logiciel"
}
INDEX 34
{
   REFERENCE CANCEL
   TEXT_ENGLISH "CANCEL"
   TEXT_GERMAN "LÖSCHEN"
   TEXT_FRENCH "ANNULER"
}
INDEX 35
{
   REFERENCE OUTFIT
   TEXT_ENGLISH "OUTFIT"
   TEXT_GERMAN "AUSRÜSTUNG"
   TEXT_FRENCH "EQUIPEMENT"
}
INDEX 36
{
   REFERENCE MO
   TEXT_ENGLISH "MISSION OBJECTIVES"
   TEXT_GERMAN "MISSIONSZIELE"
   TEXT_FRENCH "OBJECTIFS DE LA MISSION"
}
INDEX 37
{
   REFERENCE MULTIPLAYER
   TEXT_ENGLISH "MULTIPLAYER"
   TEXT_GERMAN "MEHRSPIELER"
   TEXT_FRENCH "MULTIJOUEUR"
}
INDEX 38
{
   REFERENCE GAME
   TEXT_ENGLISH "GAME"
   TEXT_GERMAN "SPIEL"
   TEXT_FRENCH "PARTIE"
}
INDEX 39
{
   REFERENCE OPTIONS
   TEXT_ENGLISH "OPTIONS"
   TEXT_GERMAN "OPTIONEN"
   TEXT_FRENCH "OPTIONS"
}
INDEX 40
{
   REFERENCE PARENTAL
   TEXT_ENGLISH "VIOLENCE LOCK"
   TEXT_GERMAN "GEWALTSPERRE"
   TEXT_FRENCH "VERROU ANTI-VIOLENCE"
}
INDEX 41
{
   REFERENCE STATS
   TEXT_ENGLISH "DISPLAY GAME STATISTICS"
   TEXT_GERMAN "SPIELSTATISTIKEN ANZEIGEN"
   TEXT_FRENCH "AFFICHER STATISTIQUES"
}
INDEX 42
{
   REFERENCE QUIT
   TEXT_ENGLISH "EXIT GAME"
   TEXT_GERMAN "SPIEL VERLASSEN"
   TEXT_FRENCH "QUITTER LE JEU"
}
INDEX 43
{
   REFERENCE RETURN_HOME
   TEXT_ENGLISH "RETURN TO MAIN PAGE"
   TEXT_GERMAN "ZURÜCK ZUM HAUPTMENÜ"
   TEXT_FRENCH "REVENIR A LA PAGE PRINCIPALE"
}
INDEX 44
{
   REFERENCE RETURN
   TEXT_ENGLISH "PREVIOUS PAGE"
   TEXT_GERMAN "VORHERIGE SEITE"
   TEXT_FRENCH "PAGE PRECEDENTE"
}
INDEX 45
{
   REFERENCE RETURN_TO_GAME
   TEXT_ENGLISH "RETURN TO GAME"
   TEXT_GERMAN "ZURÜCK ZUM SPIEL"
   TEXT_FRENCH "REVENIR A LA PARTIE"
}
INDEX 46
{
   REFERENCE NEW_GAME
   TEXT_ENGLISH "THIS WILL ONLY TAKE EFFECT AFTER STARTING A NEW GAME"
   TEXT_GERMAN "AKTIVIERUNG ERFOLGT ERST NACH START EINES NEUEN SPIELS"
   TEXT_FRENCH "CES OPTIONS PRENDRONT EFFET AU DEMARRAGE D'UNE NOUVELLE PARTIE"
}
INDEX 47
{
   REFERENCE ADVANCED
   TEXT_ENGLISH "IF YOUR CARD DOES NOT SUPPORT THIS SETTING IT WILL REVERT TO DEFAULT"
   TEXT_GERMAN "UNTERSTÜTZT IHRE KARTE DIESE EINSTELLUNG NICHT, WIRD AUTOMATISCH DIE STANDARDEINSTELLUNG WIEDERHERGESTELLT."
   TEXT_FRENCH "SI VOTRE CARTE NE SUPPORTE PAS CE REGLAGE, LE SYSTEME APPLIQUERA L'OPTION PAR DEFAUT"
}
INDEX 48
{
   REFERENCE GMH
   TEXT_ENGLISH "GET MAIL HERE"
   TEXT_GERMAN "LESEN SIE HIER IHRE MAIL"
   TEXT_FRENCH "RECEVOIR COURRIER"
}
INDEX 49
{
   REFERENCE ALTER_KEYS
   TEXT_ENGLISH "ALTER KEY BINDINGS"
   TEXT_GERMAN "TASTENBELEGUNGEN ÄNDERN"
   TEXT_FRENCH "MODIFIER PROGRAMMATION CLAVIER"
}
INDEX 50
{
   REFERENCE ALTER_DISPLAY
   TEXT_ENGLISH "ALTER DISPLAY SETTINGS"
   TEXT_GERMAN "ANZEIGE ÄNDERN"
   TEXT_FRENCH "MODIFIER PARAMETRES AFFICHAGE"
}
INDEX 51
{
   REFERENCE ALTER_AUDIO
   TEXT_ENGLISH "ALTER AUDIO SETTINGS"
   TEXT_GERMAN "AUDIO-EINSTELLUNGEN ÄNDERN"
   TEXT_FRENCH "MODIFIER PARAMETRES AUDIO"
}
INDEX 52
{
   REFERENCE ADJUST_DYNAMIC
   TEXT_ENGLISH "ADJUST DYNAMIC SCALABILITY"
   TEXT_GERMAN "DYNAMISCHE DETAILS ANPASSEN"
   TEXT_FRENCH "REGLAGES DYNAMIQUES"
}
INDEX 53
{
   REFERENCE MISC
   TEXT_ENGLISH "MISCELLANEOUS OPTIONS"
   TEXT_GERMAN "VERSCHIEDENE OPTIONEN"
   TEXT_FRENCH "OPTIONS DIVERSES"
}
INDEX 54
{
   REFERENCE APPLY
   TEXT_ENGLISH "APPLY"
   TEXT_GERMAN "ÜBERNEHMEN"
   TEXT_FRENCH "APPLIQUER"
}
INDEX 55
{
   REFERENCE RESET
   TEXT_ENGLISH "RESET"
   TEXT_GERMAN "ZURÜCKSETZEN"
   TEXT_FRENCH "REINITIALISER"
}
INDEX 56
{
   REFERENCE KEYB1
   TEXT_ENGLISH "Key Bindings"
   TEXT_GERMAN "Die Tastenbelegungen"
   TEXT_FRENCH "Programmation"
}
INDEX 57
{
   REFERENCE KEYB2
   TEXT_ENGLISH "Have Been Saved"
   TEXT_GERMAN "wurden gespeichert."
   TEXT_FRENCH "clavier enregistrée"
}
INDEX 58
{
   REFERENCE OBJS
   TEXT_ENGLISH "OBJECTIVES"
   TEXT_GERMAN "ZIELE"
   TEXT_FRENCH "OBJECTIFS"
}
INDEX 59
{
   REFERENCE SL
   TEXT_ENGLISH "Saves Left"
   TEXT_GERMAN "Restliche Speichermöglichkeiten"
   TEXT_FRENCH "Enregistrements restants"
}
INDEX 60
{
   REFERENCE PC1
   TEXT_ENGLISH "Password Has Been"
   TEXT_GERMAN "Passwort wurde"	\n"
   TEXT_FRENCH "Le mot de passe a "
}
INDEX 61
{
   REFERENCE PC2
   TEXT_ENGLISH "Changed"
   TEXT_GERMAN "geändert"
   TEXT_FRENCH "changé"
}
INDEX 62
{
   REFERENCE PCF1
   TEXT_ENGLISH "Failed!"
   TEXT_GERMAN "Fehlgeschlagen!"
   TEXT_FRENCH "Echec !"
}
INDEX 63
{
   REFERENCE PCF2
   TEXT_ENGLISH "Password Unchanged"
   TEXT_GERMAN "Passwort ungeändert"
   TEXT_FRENCH "Mot de passe inchangé"
}
INDEX 64
{
   REFERENCE EO
   TEXT_ENGLISH "*** EYES ONLY ***"
   TEXT_GERMAN "*** VERTRAULICH ***"
   TEXT_FRENCH "*** VISUEL UNIQUEMENT ***"
}
INDEX 65
{
   REFERENCE LOADING
   TEXT_ENGLISH "Loading"
   TEXT_GERMAN "Ladevorgang"
   TEXT_FRENCH "Chargement"
}
INDEX 66
{
   REFERENCE DLING
   TEXT_ENGLISH "Downloading"
   TEXT_GERMAN "Download läuft ..."
   TEXT_FRENCH "Téléchargement"
}
INDEX 67
{
   REFERENCE ENTERKEY
   TEXT_ENGLISH "Please Enter Your Personal CD Key"
   TEXT_GERMAN "Bitte geben Sie Ihren persönlichen CD-Key ein."
   TEXT_FRENCH "Veuillez saisir votre code CD personnel"
}
INDEX 68
{
   REFERENCE PRIVATE
   TEXT_ENGLISH "(Remember To Keep This Key Private)"
   TEXT_GERMAN "(Denken Sie daran, diesen Key an einem sicheren Ort aufzubewaren.)"
   TEXT_FRENCH "(Gardez pour vous ce code confidentiel)"
}
INDEX 69
{
   REFERENCE INVKEY
   TEXT_ENGLISH "Invalid CD Key!"
   TEXT_GERMAN "Ungültiger CD-Key!"
   TEXT_FRENCH "Code CD invalide !"
}
INDEX 70
{
   REFERENCE INVKEY2
   TEXT_ENGLISH "Please Try Again"
   TEXT_GERMAN "Bitte versuchen Sie es noch einmal"
   TEXT_FRENCH "Veuillez réessayer"
}
INDEX 71
{
   REFERENCE OBJ_TICKER
   TEXT_ENGLISH "*** CURRENT MISSION OBJECTIVES *** ITEMS CARRIED ***"
   TEXT_GERMAN "*** AKTUELLE MISSIONSZIELE *** GEWÄHLTE GEGENSTÄNDE ***"
   TEXT_FRENCH "*** OBJECTIFS DE LA MISSION ACTUELLE *** ACCESSOIRES TRANSPORTES ***"
}
INDEX 72
{
   REFERENCE DISCLAIMER1D
   NOTES "The french asked for an extra line in the disclaimer\n\nThis is it."
   TEXT_ENGLISH " "
}
INDEX 73
{
   REFERENCE EXITPROG
   TEXT_ENGLISH "QUIT GAME"
   TEXT_GERMAN "SPIEL BEENDEN"
   TEXT_FRENCH "QUITTER LE JEU"
}
INDEX 74
{
   REFERENCE THEEND
   TEXT_ENGLISH "THE END"
   TEXT_GERMAN "ENDE"
   TEXT_FRENCH "FIN"
}
INDEX 75
{
   REFERENCE MAIN_TICKER_LV
   NOTES "The ticker file when you first enter the game for low violence"
   TEXT_ENGLISH "*** WELCOME TO SOLDIER OF FORTUNE ***\n!!TO BEGIN A NEW GAME, CLICK THE 'GAME' ICON!!\n*** TO CHANGE VIDEO, CONTROL, AND AUDIO OPTIONS, PRESS THE 'OPTIONS' ICON *** \n!! TO REPORT ANY PROBLEMS USE THE MESSAGEBOARD AT HTTP://SOF.RAVENSOFT.COM !!\n"
   TEXT_GERMAN "*** HERZLICH WILLKOMMEN ZU SOLDIER OF FORTUNE ***\n!!UM EIN NEUES SPIEL ZU STARTEN, KLICKEN SIE AUF DAS 'SPIEL'-ICON!!\n*** UM DIE GRAFIK-, STEUERUNGS- UND AUDIO-OPTIONEN ZU ÄNDERN, KLICKEN SIE AUF DAS 'OPTIONEN'-ICON. ***\n!!WOLLEN SIE UNS AUF ETWAIGE PROBLEME AUFMERKSAM MACHEN, TUN SIE DIES BITTE ÜBER DAS MESSAGEBOARD UNTER HTTP://SOF.RAVENSOFT.COM!!***\n"
   TEXT_FRENCH "*** BIENVENUE A SOLDIER OF FORTUNE ***\n!! POUR DEMARRER UNE NOUVELLE PARTIE, CLIQUEZ SUR L'ICONE 'PARTIE' !!\n*** POUR CHANGER LES PARAMETRES VIDEO, AUDIO ET DE CONTROLE, CLIQUEZ SUR L'ICONE 'OPTIONS' ***\n*** FAITES-NOUS PART DE VOS PROBLEMES SUR LE SITE HTTP://SOF.RAVENSOFT.COM ***\n"
}
INDEX 76
{
   REFERENCE MBRIEF
   TEXT_ENGLISH "MISSION BRIEFING"
   TEXT_GERMAN "MISSIONSANWEISUNGEN"
   TEXT_FRENCH "BRIEFING MISSION"
}
