VERSION 1
ID 107
REFERENCE SIB1
DESCRIPTION "Siberia 1 Level Strings"
COUNT 20
INDEX 0
{
   FLAGS SP_FLAG_CAPTIONED
   REFERENCE S11D1
   TEXT_ENGLISH "JOHN:  Old fortifications.  Better keep my eyes open."
   TEXT_GERMAN "JOHN: Eine alte Festung. Ich halte besser meine Augen offen."
   TEXT_FRENCH "JOHN:  D'anciennes fortifications. Je ferais mieux d'ouvrir l'oeil."
}
INDEX 1
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE PUMP
   TEXT_ENGLISH "COMPUTER:  < Pump will reactivate in 45 seconds. >"
   TEXT_GERMAN "COMPUTER: < Reaktiviert Pumpe in 45 Sekunden. >"
   TEXT_FRENCH "ORDINATEUR : < Réactivation de la pompe dans 45 secondes. >"
}
INDEX 2
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE SECONDS
   TEXT_ENGLISH "seconds. >"
   TEXT_GERMAN "Sekunden. >"
   TEXT_FRENCH "secondes. >"
}
INDEX 3
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE MINUTES
   TEXT_ENGLISH "Minutes. >"
   TEXT_GERMAN "Minuten. >"
   TEXT_FRENCH "minutes. >"
}
INDEX 4
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE TEN
   TEXT_ENGLISH "10"
   TEXT_GERMAN "10"
   TEXT_FRENCH "10"
}
INDEX 5
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE NINE
   TEXT_ENGLISH "9"
   TEXT_GERMAN "9"
   TEXT_FRENCH "9"
}
INDEX 6
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE EIGHT
   TEXT_ENGLISH "8"
   TEXT_GERMAN "8"
   TEXT_FRENCH "8"
}
INDEX 7
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE SEVEN
   TEXT_ENGLISH "7"
   TEXT_GERMAN "7"
   TEXT_FRENCH "7"
}
INDEX 8
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE SIX
   TEXT_ENGLISH "6"
   TEXT_GERMAN "6"
   TEXT_FRENCH "6"
}
INDEX 9
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE FIVE
   TEXT_ENGLISH "5"
   TEXT_GERMAN "5"
   TEXT_FRENCH "5"
}
INDEX 10
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE FOUR
   TEXT_ENGLISH "4"
   TEXT_GERMAN "4"
   TEXT_FRENCH "4"
}
INDEX 11
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE THREE
   TEXT_ENGLISH "3"
   TEXT_GERMAN "3"
   TEXT_FRENCH "3"
}
INDEX 12
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE TWO
   TEXT_ENGLISH "2"
   TEXT_GERMAN "2"
   TEXT_FRENCH "2"
}
INDEX 13
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE ONE
   TEXT_ENGLISH "1"
   TEXT_GERMAN "1"
   TEXT_FRENCH "1"
}
INDEX 14
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE THIRTY
   TEXT_ENGLISH "30"
   TEXT_GERMAN "30"
   TEXT_FRENCH "30"
}
INDEX 15
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE FORTYFIVE
   TEXT_ENGLISH "45"
   TEXT_GERMAN "45"
   TEXT_FRENCH "45"
}
INDEX 16
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE SIXTY
   TEXT_ENGLISH "60"
   TEXT_GERMAN "60"
   TEXT_FRENCH "60"
}
INDEX 17
{
   FLAGS SP_FLAG_TYPEAMATIC
   REFERENCE INTRO
   TEXT_ENGLISH "Location:  Uedineniya, Siberia\nDate:  10/21/00\nTime:  23:20\n"
   TEXT_GERMAN "Ort: Uedinien, Saburien\nDatum: 21.10.00\nZeit: 23.20 Uhr"
   TEXT_FRENCH "Site :  Uedineniya, Sibérie\nDate :  21/10/00\nHeure :  23:20\n"
}
INDEX 18
{
   FLAGS SP_FLAG_CENTERED
   REFERENCE ACCESS
   TEXT_ENGLISH "ACCESS DENIED: FUEL MUST BE FLUSHED FROM PIPE SYSTEM BEFORE OPENING HATCH\n"
   TEXT_GERMAN "ZUGANG VERWEIGERT: DER TREIBSTOFF MUSS ERST AUS DEN PIPELINES GESPÜLT WERDEN, BEVOR DIE TÜR GEÖFFNET WIRD."
   TEXT_FRENCH "ACCES REFUSE : LE PETROLE DOIT ETRE EVACUE DU SYSTEME D'ALIMENTATION AVANT D'OUVRIR LA VANNE."
}
INDEX 19
{
   FLAGS SP_FLAG_CENTERED
   REFERENCE LOCKED
   TEXT_ENGLISH "LOCKED"
   TEXT_GERMAN "VERSCHLOSSEN"
   TEXT_FRENCH "VERROUILLE"
}
