VERSION 1
ID 115
REFERENCE SIB3
DESCRIPTION "Siberia 3 Level Strings"
COUNT 20
INDEX 0
{
   FLAGS SP_FLAG_CAPTIONED SP_FLAG_ALWAYS_PRINT
   REFERENCE C25D1
   TEXT_ENGLISH "COMPUTER: < Main power grid failure. >"
   TEXT_GERMAN "COMPUTER: < Hauptstromnetz ausgefallen. >"
   TEXT_FRENCH "ORDINATEUR: < Coupure d'alimentation principale. >"
}
INDEX 1
{
   FLAGS SP_FLAG_CAPTIONED
   REFERENCE C25D2
   TEXT_ENGLISH "JOHN: NEST EGG is going down with this place. Better get the hell out."
   TEXT_GERMAN "JOHN: NESTHÄKCHEN geht mit diesem Ort hier unter. Verschwinden Sie lieber."
   TEXT_FRENCH "JOHN: NEST EGG va être détruit avec le reste. Inutile de s'attarder."
}
INDEX 2
{
   FLAGS SP_FLAG_CENTERED
   TEXT_ENGLISH "INVALID PASSCODE"
   TEXT_GERMAN "UNGÜLTIGES PASSWORT"
   TEXT_FRENCH "CODE D'ACCES INVALIDE"
}
INDEX 3
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE CRITICAL
   TEXT_ENGLISH "< CRITICAL MASS IN"
   TEXT_GERMAN "< EXPLOSION IN"
   TEXT_FRENCH "< MASSE CRITIQUE DANS"
}
INDEX 4
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE MINUTES
   TEXT_ENGLISH "MINUTES >"
   TEXT_GERMAN "MINUTEN >"
   TEXT_FRENCH "MINUTES >"
}
INDEX 5
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE CRITICAL3
   TEXT_ENGLISH "< PLANT MELTDOWN IN "
   TEXT_GERMAN "< WERKZERSTÖRUNG IN "
   TEXT_FRENCH "< DESTRUCTION DE L'USINE DANS "
}
INDEX 6
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE CRITICAL4
   TEXT_ENGLISH "< 1 MINUTE TO CRITICAL MASS >"
   TEXT_GERMAN "< 1 MINUTE BIS ZUR EXPLOSION >"
   TEXT_FRENCH "< MASSE CRITIQUE DANS 1 MINUTE >"
}
INDEX 7
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE SECONDS
   TEXT_ENGLISH "SECONDS >"
   TEXT_GERMAN "SEKUNDEN >"
   TEXT_FRENCH "SECONDES >"
}
INDEX 8
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE THIRTY
   TEXT_ENGLISH "30"
   TEXT_GERMAN "30"
   TEXT_FRENCH "30"
}
INDEX 9
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE TEN
   TEXT_ENGLISH "10"
   TEXT_GERMAN "10"
   TEXT_FRENCH "10"
}
INDEX 10
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE NINE
   TEXT_ENGLISH "9"
   TEXT_GERMAN "9"
   TEXT_FRENCH "9"
}
INDEX 11
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE EIGHT
   TEXT_ENGLISH "8"
   TEXT_GERMAN "8"
   TEXT_FRENCH "8"
}
INDEX 12
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE SEVEN
   TEXT_ENGLISH "7"
   TEXT_GERMAN "7"
   TEXT_FRENCH "7"
}
INDEX 13
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE SIX
   TEXT_ENGLISH "6"
   TEXT_GERMAN "6"
   TEXT_FRENCH "6"
}
INDEX 14
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE FIVE
   TEXT_ENGLISH "5"
   TEXT_GERMAN "5"
   TEXT_FRENCH "5"
}
INDEX 15
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE FOUR
   TEXT_ENGLISH "4"
   TEXT_GERMAN "4"
   TEXT_FRENCH "4"
}
INDEX 16
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE THREE
   TEXT_ENGLISH "3"
   TEXT_GERMAN "3"
   TEXT_FRENCH "3"
}
INDEX 17
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE TWO
   TEXT_ENGLISH "2"
   TEXT_GERMAN "2"
   TEXT_FRENCH "2"
}
INDEX 18
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE ONE
   TEXT_ENGLISH "1"
   TEXT_GERMAN "1"
   TEXT_FRENCH "1"
}
INDEX 19
{
   FLAGS SP_FLAG_CENTERED SP_FLAG_ALWAYS_PRINT
   REFERENCE THIRTYSEC
   TEXT_ENGLISH "< THIRTY SECONDS >"
   TEXT_GERMAN "< 30 SEKUNDEN >"
   TEXT_FRENCH "< TRENTE SECONDES >"
}
