VERSION 1
ID 2
REFERENCE WEAPONS
DESCRIPTION "General Weapon Strings"
COUNT 13
INDEX 0
{
   REFERENCE KNIFE
   TEXT_ENGLISH "KNIFE"
   TEXT_GERMAN "MESSER"
   TEXT_FRENCH "COUTEAU"
}
INDEX 1
{
   REFERENCE PISTOL1
   TEXT_ENGLISH "9MM PISTOL"
   TEXT_GERMAN "9MM-PSTLE"
   TEXT_FRENCH "PISTOL. 9MM"
}
INDEX 2
{
   REFERENCE PISTOL2
   TEXT_ENGLISH ".44 PISTOL"
   TEXT_GERMAN ".44-PISTOLE"
   TEXT_FRENCH "PISTOL. 44"
}
INDEX 3
{
   REFERENCE SHOTGUN
   TEXT_ENGLISH "SHOTGUN"
   TEXT_GERMAN "SCHROTFL."
   TEXT_FRENCH "FUSIL"
}
INDEX 4
{
   REFERENCE SNIPER
   TEXT_ENGLISH "SNIPER R"
   TEXT_GERMAN "SCHARFSCH."
   TEXT_FRENCH "F. SNIPER"
}
INDEX 5
{
   REFERENCE ASSAULTRIFLE
   TEXT_ENGLISH "SMG"
   TEXT_GERMAN "MP"
   TEXT_FRENCH "SMG"
}
INDEX 6
{
   REFERENCE MACHINEGUN
   TEXT_ENGLISH "HEAVY MG"
   TEXT_GERMAN "SCHWERES MG"
   TEXT_FRENCH "MITR. LDE"
}
INDEX 7
{
   REFERENCE MACHINEPISTOL
   TEXT_ENGLISH "SUP. SMG"
   TEXT_GERMAN "MP (SCHALLD.)"
   TEXT_FRENCH "SMG SILENC."
}
INDEX 8
{
   REFERENCE AUTOSHOTGUN
   TEXT_ENGLISH "SLGTHRWR"
   TEXT_GERMAN "METALLSCHL."
   TEXT_FRENCH "LANCE-SHR."
}
INDEX 9
{
   REFERENCE FLAMEGUN
   TEXT_ENGLISH "FLAME GUN"
   TEXT_GERMAN "FLAMMENGEW."
   TEXT_FRENCH "LANCE-FLAM."
}
INDEX 10
{
   REFERENCE ROCKET
   TEXT_ENGLISH "RCK LNCH"
   TEXT_GERMAN "RAKETENWERF."
   TEXT_FRENCH "LANCE-ROQ."
}
INDEX 11
{
   REFERENCE MICROWAVEPULSE
   TEXT_ENGLISH "MPG"
   TEXT_GERMAN "STRAHLENGEW."
   TEXT_FRENCH "FMO"
}
INDEX 12
{
   REFERENCE NONE
   TEXT_ENGLISH "NONE"
   TEXT_GERMAN "KEINE"
   TEXT_FRENCH "AUCUNE"
}
