VERSION 1
ID 5
REFERENCE SV_TEXT
DESCRIPTION "Server console text"
COUNT 13
INDEX 0
{
   REFERENCE DF_STANDARD_FLAGS
   TEXT_ENGLISH "\nStandard deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Weapons Stay        %s     Weapons remain after being picked up\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   No weapon reload    %s     Weapons do not reload\n08)   Teamplay            %s     Teamplay is enabled\n09)   No Friendly Fire    %s     Player's fire can't hurt teamates\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armor            %s     No armor pickups spawned in level\n12)   Infinite Ammo       %s     Weapons use no ammo\n13)   Spinning Weapons    %s     Weapon pickups rotate a la Quake\n14)   Bullet Only         %s     Bullet only weapons\n15)   Unused              %s\n16)   Unused              %s\n*16"
   TEXT_GERMAN "\nStandard-Deathmatch-Einstellungen lauten wie folgt:\n\nNr.   Name               Wert   Bedeutung der aktivierten Einstellungen\n---   ----               -----   -------------------------------------\n01)   Keine Energie       %s   Keine Energie-Pick-Ups im Level verfügbar\n02)   Keine Gegenstände   %s  Keine Gegenstände im Level verfügbar\n03)   Waffenverbleib      %s    Waffen verbleiben nach Aufsammlung \n04)   Kein Sturzschaden   %s     Spieler erfährt beim Sturz keinen Schaden\n05)   Realist. Auswirkung  %s Realist. Beeinträchtigung des Körpers\n06)   Gleicher Level      %s     Nächster Level ist immer wie aktueller Level\n07)   Kein Nachladen      %s     Waffen laden nicht nach\n08)   Teamplay            %s     Teamplay ist aktiviert\n09)   Kein Teamfeuer      %s     Schüsse verletzen keine Teampartner\n10)   Zwangseinstieg      %s Getötete Spieler kommen sof. wieder ins Spiel \n11)   Keine Rüstung       %s    Keine Rüstungs-Pick-Ups im Level verfügbar\n12)   Unendl. Munition    %s    Waffen verbrauchen keine Munition\n13)   Waffenrotation      %s     Waffen-Pick-Ups rotieren\n14)   Patronenwaffen      %s      Nur Waffen mit Patronenmunition\n15)   Nicht verwendet     %s\n*15"
   TEXT_FRENCH "\nDrapeaux de match à mort standard :\n\nnum   nom               valeur   signification\n---   ---               ------   -------------------------------------\n01)   0 santé             %s     0 kit médical récupérable dans le niveau\n02)   0 accessoire        %s     Aucun accessoire récupérable dans le niveau\n03)   Armes perm.         %s     Les armes restent après récupération\n04)   0 dom. chute        %s     Les joueurs sortent indemnes des chutes\n05)   Bles. réalistes     %s     Blessures corporelles réalistes\n06)   Même niveau         %s     Niveau suivant identique à l'actuel\n07)   0 rechargement      %s     Les armes ne se rechargent pas\n08)   Jeu Equipe          %s     Jeu en équipe activé\n09)   0 tir ami           %s     Les joueurs ne peuvent blesser leurs équipiers\n10)   Forcer régén.       %s     Les joueurs régénèrent immédiatement\n11)   0 blindage          %s     Pas de blindage récupérable dans le niveau\n12)   Munitions illim.    %s     Munitions illimitées pour les armes\n13)   Rotation Armes      %s     Armes en rotation comme dans Quake\n14)   Armes à feu         %s     Armes à feu uniquement\n15)   Inutilisé           %s\n*15"
   TEXT_BRITISH "\nStandard deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Weapons Stay        %s     Weapons remain after being picked up\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   No weapon reload    %s     Weapons do not reload\n08)   Teamplay            %s     Teamplay is enabled\n09)   No Friendly Fire    %s     Player's fire can't hurt teamates\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armour           %s     No armour pickups spawned in level\n12)   Infinite Ammo       %s     Weapons use no ammo\n13)   Spinning Weapons    %s     Weapon pickups rotate a la Quake\n14)   Bullet Only         %s     Bullet only weapons\n15)   Unused              %s\n*15"
}
INDEX 1
{
   REFERENCE DF_ASSASSIN_FLAGS
   TEXT_ENGLISH "\nAssassin deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Weapons Stay        %s     Weapons remain after being picked up\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   No weapon reload    %s     Weapons do not reload\n08)   Unused              %s\n09)   Unused              %s\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armor            %s     No armor pickups spawned in level\n12)   Infinite Ammo       %s     Weapons use no ammo\n13)   Spinning Weapons    %s     Weapon pickups rotate a la Quake\n14)   Bullet Only         %s     Bullet only weapons\n15)   Unused              %s\n16)   Unused              %s\n*16"
   TEXT_GERMAN "\nKopfgeldjäger-Deathmatch-Einstellungen lauten wie folgt:\n\nNr.   Name                Wert   Bedeutung der aktivierten Einstellungen\n---   ----               -----   -------------------------------------\n01)   Keine Energie       %s   Keine Energie-Pick-Ups im Level verfügbar\n02)   Keine Gegenstände   %s   Keine Gegenstände im Level verfügbar\n03)   Waffenverbleib      %s     Waffen verbleiben nach Aufsammlung\n04)   Kein Sturzschaden   %s     Spieler erfährt beim Sturz keinen Schaden\n05)   Realist. Auswirkung %s  Realist. Beeinträchtigung des Körpers\n06)   Gleicher Level      %s     Nächster Level ist immer wie aktueller Level\n07)   Kein Nachladen      %s     Waffen laden nicht nach\n08)   Nicht verwendet     %s\n09)   Nicht verwendet     %s\n10)   Zwangseinstieg      %s  Getötete Spieler kommen sof. wieder ins Spiel \n11)   Keine Rüstung       %s   Keine Rüstungs-Pick-Ups im Level verfügbar\n12)   Unendl. Munition    %s    Waffen verbrauchen keine Munition \n13)   Waffenrotation      %s     Waffen-Pick-Ups rotieren\n14)   Patronenwaffen      %s     Nur Waffen mit Patronenmunition\n15)   Nicht verwendet     %s\n*15\n\n"
   TEXT_FRENCH "\nDrapeaux de match à mort assassin :\n\nnum   nom               valeur   signification\n---   ---               ------   -------------------------------------\n01)   0 santé             %s     0 kit médical récupérable dans le niveau\n02)   0 accessoire        %s     Aucun accessoire récupérable dans le niveau\n03)   Armes perm.         %s     Les armes restent après récupération\n04)   0 dom. chute        %s     Les joueurs sortent indemnes des chutes\n05)   Bles. réalistes     %s     Blessures corporelles réalistes\n06)   Même niveau         %s     Niveau suivant identique à l'actuel\n07)   0 rechargement      %s     Les armes ne se rechargent pas\n08)   Inutilisé	          %s\n09)   Inutilisé	          %s\n10)   Forcer régén.       %s     Les joueurs régénèrent immédiatement\n11)   0 blindage          %s     Pas de blindage récupérable dans le niveau\n12)   Munitions illim.    %s     Munitions illimitées pour les armes\n13)   Rotation Armes      %s     Armes en rotation comme dans Quake\n14)   Armes à feu         %s     Armes à feu uniquement\n15)   Inutilisé           %s\n*15"
   TEXT_BRITISH "\nAssassin deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Weapons Stay        %s     Weapons remain after being picked up\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   No weapon reload    %s     Weapons do not reload\n08)   Unused              %s\n09)   Unused              %s\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armour           %s     No armour pickups spawned in level\n12)   Infinite Ammo       %s     Weapons use no ammo\n13)   Spinning Weapons    %s     Weapon pickups rotate a la Quake\n14)   Bullet Only         %s     Bullet only weapons\n15)   Unused              %s\n*15"
}
INDEX 2
{
   REFERENCE DF_ARSENAL_FLAGS
   TEXT_ENGLISH "\nArsenal deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Unused              %s\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   Unused              %s\n08)   Unused              %s\n09)   Unused              %s\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armor            %s     No armor pickups spawned in level\n12)   Unused              %s\n13)   Unused              %s\n14)   Unused              %s\n15)   Unused              %s\n16)   Unused              %s\n*16"
   TEXT_GERMAN "Arsenal-Deathmatch-Einstellungen lauten wie folgt:\n\nNr   Name               Wert   Bedeutung der aktivierten Einstellungen\n---   ----               -----   -------------------------------------\n01)   Keine Energie       %s     Keine Energie-Pick-Ups im Level verfügbar\n02)   Keine Gegenstände   %s   Keine Gegenstände im Level verfügbar\n03)   Nicht verwendet     %s\n04)   Kein Sturzschaden   %s     Spieler erfährt beim Sturz keinen Schaden\n05)   Realist. Auswirkung %s    Realist. Beeinträchtigung des Körpers\n06)   Gleicher Level      %s     Nächster Level ist wie der aktuelle Level\n07)   Nicht verwendet     %s\n08)   Nicht verwendet     %s\n09)   Nicht verwendet     %s\n10)   Zwangseinstieg      %s  Getötete Spieler kommen sof. wieder ins Spiel 11)   Keine Rüstung       %s   Keine Rüstungs-Pick-Ups im Level verfügbar\n12)   Nicht verwendet     %s\n13)   Nicht verwendet     %s\n14)   Nicht verwendet     %s\n15)   Nicht verwendet     %s\n*15"
   TEXT_FRENCH "\nDrapeaux de match à mort arsenal :\n\nnum   nom               valeur   signification\n---   ---               ------   -------------------------------------\n01)   0 santé             %s     0 kit médical récupérable dans le niveau\n02)   0 accessoire        %s     Aucun accessoire récupérable dans le niveau\n03)   Inutilisé           %s\n04)   0 dom. chute        %s     Les joueurs sortent indemnes des chutes\n05)   Bles. réalistes     %s     Blessures corporelles réalistes\n06)   Même niveau         %s     Niveau suivant identique au courant\n07)   Inutilisé	 	  %s\n08)   Inutilisé	          %s\n09)   Inutilisé	 	  %s\n10)   Forcer rég.         %s     Les joueurs régénèrent immédiatement\n11)   0 blindage          %s     Pas de blindage récupérable dans le niveau\n12)   Inutilisé           %s\n13)   Inutilisé	          %s\n14)   Inutilisé           %s\n15)   Inutilisé           %s\n*15"
   TEXT_BRITISH "\nArsenal deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Unused              %s\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   Unused              %s\n08)   Unused              %s\n09)   Unused              %s\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armour           %s     No armour pickups spawned in level\n12)   Unused              %s\n13)   Unused              %s\n14)   Unused              %s\n15)   Unused              %s\n*15"
}
INDEX 3
{
   REFERENCE DF_CTF_FLAGS
   TEXT_ENGLISH "\nCTF deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Weapons Stay        %s     Weapons remain after being picked up\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   No weapon reload    %s     Weapons do not reload\n08)   Unused              %s\n09)   No Friendly Fire    %s     Player's fire can't hurt teamates\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armor            %s     No armor pickups spawned in level\n12)   Infinite Ammo       %s     Weapons use no ammo\n13)   Spinning Weapons    %s     Weapon pickups rotate a la Quake\n14)   Bullet Only         %s     Bullet only weapons\n15)   Force Join          %s     No choice in team selection\n16)   Unused              %s\n*16"
   TEXT_GERMAN "CTF-Deathmatch-Einstellungen lauten wie folgt:\n\nNr.   Name               Wert   Bedeutung der aktivierten Einstellungen\n---   ----               -----   -------------------------------------\n01)   Keine Energie       %s     Keine Energie-Pick-Ups im Level verfügbar\n02)   Keine Gegenstände   %s   Keine Gegenstände im Level verfügbar\n03)   Waffenverbleib      %s     Waffen verbleiben nach Aufsammlung\n04)   Kein Sturzschaden   %s     Spieler erfährt beim Sturz keinen Schaden\n05)   Realist. Auswirkung %s   Realist. Beeinträchtigung des Körpers\n06)   Gleicher Level      %s     Nächster Level ist wie der aktuelle Level\n07)   Kein Nachladen      %s     Die Waffen laden nicht nach\n08)   Nicht verwendet     %s\n09)   Kein Teamfeuer      %s     Schüsse verletzen keine Teampartner\n10)   Zwangseinstieg      %s  Getötete Spieler kommen sof. wieder ins Spiel \n11)   Keine Rüstung       %s    Keine Rüstungs-Pick-Ups im Level verfügbar\n12)   Unendl. Munition    %s    Waffen verbrauchen keine Munition\n13)   Waffenrotation      %s     Waffen-Pick-Ups rotieren\n14)   Patronenwaffen      %s     Nur Waffen mit Patronenmunition\n15)   Autom. Teamzuw.     %s   Keine Wahl bei Teamauswahl\n*15"
   TEXT_FRENCH "\nDrapeaux de match à mort CDD :\n\nnum   nom               valeur   signification\n---   ---               ------   -------------------------------------\n01)   0 santé             %s     0 kit médical récupérable dans le niveau\n02)   0 accessoire        %s     Aucun accessoire récupérable dans le niveau\n03)   Armes perm.         %s     Les armes restent après récupération\n04)   0 dom. chute        %s     Les joueurs sortent indemnes des chutes\n05)   Bles. réalistes     %s     Blessures corporelles réalistes\n06)   Même niveau         %s     Niveau suivant identique à l'actuel\n07)   0 rechargement      %s     Les armes ne se rechargent pas\n08)   Inutilisé           %s\n09)   0 tir ami           %s     Les joueurs ne peuvent blesser leurs équipiers\n10)   Forcer rég.         %s     Les joueurs régénèrent immédiatement\n11)   0 blindage          %s     Pas de blindage récupérable dans le niveau\n12)   Munitions illim.    %s     Munitions illimitées pour les armes\n13)   Rotation Armes      %s     Armes en rotation comme dans Quake\n14)   Armes à feu         %s     Armes à feu uniquement\n15)   Equipe imposée      %s     Pas de choix dans la sélection d'équipe\n*15"
   TEXT_BRITISH "\nCTF deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Weapons Stay        %s     Weapons remain after being picked up\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   No weapon reload    %s     Weapons do not reload\n08)   Unused              %s\n09)   No Friendly Fire    %s     Player's fire can't hurt teamates\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armour           %s     No armour pickups spawned in level\n12)   Infinite Ammo       %s     Weapons use no ammo\n13)   Spinning Weapons    %s     Weapon pickups rotate a la Quake\n14)   Bullet Only         %s     Bullet only weapons\n15)   Force Join          %s     No choice in team selection\n*15"
}
INDEX 4
{
   REFERENCE DF_REAL_FLAGS
   TEXT_ENGLISH "\nRealistic deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   Unused              %s\n02)   Unused              %s\n03)   Unused              %s\n04)   Unused              %s\n05)   Unused              %s\n06)   Same Level          %s     Next level always same as current\n07)   Unused              %s\n08)   Teamplay            %s     Teamplay is enabled\n09)   Unused              %s\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armor            %s     No armor pickups spawned in level\n12)   Unused              %s\n13)   Spinning Weapons    %s     Weapon pickups rotate a la Quake\n14)   Bullet Only         %s     Bullet only weapons\n15)   Unused              %s\n16)   Unused              %s\n*16"
   TEXT_GERMAN "Realistische Deathmatch-Einstellungen lauten wie folgt:\n\nNr.   Name               Wert   Bedeutung der aktivierten Einstellungen\n---   ----               -----   -------------------------------------\n01)   Nicht verwendet     %s\n02)   Nicht verwendet     %s\n03)   Nicht verwendet     %s\n04)   Nicht verwendet     %s\n05)   Nicht verwendet     %s\n06)   Gleicher Level      %s    Nächster Level ist wie der aktuelle Level\n07)   Nicht verwendet     %s\n08)   Teamplay            %s     Teamplay ist aktiviert\n09)   Nicht verwendet     %s\n10)   Zwangseinstieg      %s  Getötete Spieler kommen sof. wieder ins Spiel\n11)   Keine Rüstung       %s    Keine Rüstungs-Pick-Ups im Level verfügbar\n12)   Nicht verwendet     %s\n13)   Waffenrotation      %s     Waffen-Pick-Ups rotieren\n14)   Patronenwaffen      %s     Nur Waffen mit Patronenmunition\n15)   Nicht verwendet     %s\n*15"
   TEXT_FRENCH "\nDrapeaux de match à mort réaliste :\n\nnum   nom               valeur   signification\n---   ---		------   -------------------------------------\n01)   Inutilisé           %s\n02)   Inutilisé           %s\n03)   Inutilisé           %s\n04)   Inutilisé           %s\n05)   Inutilisé           %s\n06)   Même niveau         %s     Niveau suivant identique à l'actuel\n07)   Inutilisé           %s\n08)   Jeu Equipe          %s     Jeu en équipe activé\n09)   Inutilisé           %s\n10)   Forcer régén.       %s     Les joueurs régénèrent immédiatement\n11)   0 blindage          %s     Pas de blindage récupérable dans le niveau\n12)   Inutilisé           %s\n13)   Rotation Armes      %s     Armes en rotation comme dans Quake\n14)   Armes à feu 	  %s     Armes à feu uniquement\n15)   Inutilisé           %s\n*15                         		\n"
}
INDEX 5
{
   REFERENCE DF_CONTROL_FLAGS
   TEXT_ENGLISH "\nCONTROL deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Weapons Stay        %s     Weapons remain after being picked up\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   No weapon reload    %s     Weapons do not reload\n08)   Unused              %s\n09)   No Friendly Fire    %s     Player's fire can't hurt teamates\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armor            %s     No armor pickups spawned in level\n12)   Infinite Ammo       %s     Weapons use no ammo\n13)   Spinning Weapons    %s     Weapon pickups rotate a la Quake\n14)   Bullet Only         %s     Bullet only weapons\n15)   Force Join          %s     No choice in team selection\n16)   Unused              %s\n*16"
   TEXT_GERMAN "*0"
   TEXT_FRENCH "*0"
}
INDEX 6
{
   REFERENCE DF_CONQUER_FLAGS
   TEXT_ENGLISH "\nConquer deathmatch flags are:\n\nnum   name               value   definition of what flag does when set\n---   ----               -----   -------------------------------------\n01)   No Health           %s     No health pickups spawned in level\n02)   No Items            %s     No item pickups in spawned in level\n03)   Weapons Stay        %s     Weapons remain after being picked up\n04)   No Falling Damage   %s     Player takes no damage from falling\n05)   Realistic Damage    %s     Realistic, body part specific damage\n06)   Same Level          %s     Next level always same as current\n07)   No weapon reload    %s     Weapons do not reload\n08)   Teamplay            %s     Teamplay is enabled\n09)   No Friendly Fire    %s     Player's fire can't hurt teamates\n10)   Force Respawn       %s     Players respawn immediately after dying\n11)   No Armor            %s     No armor pickups spawned in level\n12)   Infinite Ammo       %s     Weapons use no ammo\n13)   Spinning Weapons    %s     Weapon pickups rotate a la Quake\n14)   Bullet Only         %s     Bullet only weapons\n15)   Force Join          %s     No choice in team selection\n16)   Team Red/Blue       %s     Choice to activate the Red/Blue team style\n*16"
   TEXT_GERMAN "*0"
   TEXT_FRENCH "*0"
}
INDEX 7
{
   REFERENCE DF_8_FLAGS
   TEXT_ENGLISH "*0"
   TEXT_GERMAN "*0"
   TEXT_FRENCH "*0"
}
INDEX 8
{
   REFERENCE DF_9_FLAGS
   TEXT_ENGLISH "*0"
   TEXT_GERMAN "*0"
   TEXT_FRENCH "*0"
}
INDEX 9
{
   REFERENCE DF_10_FLAGS
   TEXT_ENGLISH "*0"
   TEXT_GERMAN "*0"
   TEXT_FRENCH "*0"
}
INDEX 10
{
   REFERENCE SET_DMFLAGS
   TEXT_ENGLISH "Usage: set_dmflags a b c... where a, b, c etc. are numbers of deathmatch flags to be set.\n\n"
   TEXT_GERMAN "Verwendung: set_dmflags a b c... wenn a, b, c etc. Deathmatch-Einstellungen sind, die aktiviert werden müssen.\n\n"
   TEXT_FRENCH "Utilisation : set_dmflags a b c... où a, b, c etc. correspondent aux drapeaux à définir.\n\n"
}
INDEX 11
{
   REFERENCE UNSET_DMFLAGS
   TEXT_ENGLISH "Usage: unset_dmflags a b c... where a, b, c etc. are numbers of deathmatch flags to be cleared.\n"
   TEXT_GERMAN "Verwendung: unset_dmflags a b c... wenn a, b, c etc. Deathmatch-Einstellungen sind, die gelöscht werden müssen.\n"
   TEXT_FRENCH "Utilisation : unset_dmflags a b c... où a, b, c etc. correspondent aux drapeaux à effacer.\n"
}
INDEX 12
{
   REFERENCE DM_NOT_SET
   TEXT_ENGLISH "Deathmatch is not set\n"
   TEXT_GERMAN "Deathmatch ist nicht aktiviert."
   TEXT_FRENCH "Match à mort non défini\n"
}
